### ISSUE TITLE
Not found MaterialTextField and MaterialIcon in latest updated version

### ISSUE THREAD

**Issue by tp16190** [contrix09/XF-Material-Library#1]
Install latest version 1.0.3 of XF-Material-Library that added MaterialTextField and MaterialIcon from nuget package source in my visual studio 2017 for xamarin.forms projects, but i dont found these controls even it is updated. Please update nuget package source.

**Comment by contrix09** [comment]
Will check on this.

**Comment by tp16190** [comment]
Thanks for quick reply.... If any update please let me know as soon as possible as I needed it. Once again thanks for this very much useful library.

**Comment by contrix09** [comment]
The issue has been fixed. I already uploaded the newest version of the package and can now be downloaded. Turns out I forgot to rebuild the project before I created the package.
