### ISSUE TITLE
MaterialButton change after Navigation.PopModalAsync()

### ISSUE THREAD

**Issue by breakcoding** [contrix09/XF-Material-Library#10]
I use the **MaterialButton** for something, so when I click one button that a show ContenPage with the method Navigation.PushModalAsync that work fine, but when I call  await Navigation.PopModalAsync(), but before to call PopModalAsync(), I change a property of button like a BorderColor that change all the style of the button, is like the button not was a **MaterialButton** , because the modal dissapear but the button look like a native button and not like **MaterialButton** 
That something I doing bad o something with the button, because i tried everything but nothing change, sorry is weird to me that happend

**Comment by contrix09** [comment]
Will check on this. Is this in Android or iOS?
