### ISSUE TITLE
MaterialButton Error include image

### ISSUE THREAD

**Issue by thiagoparabas** [contrix09/XF-Material-Library#116]
Erro include Image in MaterialButton( Image + Text)

Android.Content.Res.Resources+NotFoundException: Resource ID #0x0

Version 1.4.1.1

**Comment by contrix09** [comment]
Be sure that your image file is included in the `resources/drawable` folders.

**Comment by thiagoparabas** [comment]
@contrix09 

Man, the image working with MaterialIconButton, not working with MaterialButton.

But I necessary Image and Text in button and MaterialIconButton there is not Text.

Please check this! 👍  Thanks.

**Comment by contrix09** [comment]
What's your image asset's file name?
