### ISSUE TITLE
No more HasHorizontalPadding

### ISSUE THREAD

**Issue by andy200486** [contrix09/XF-Material-Library#117]
I've updated to the latest version (1.4.1.1) and it seems that the property "HasHorizontalPadding" has disappeared...

**Comment by contrix09** [comment]
Hi, you can use `HorizontalPadding` property to set the left and right padding of the text field. `0` value will remove the left and right padding, just like the appearance when `HasHorizontalPadding` is set to `false`.

**Comment by andy200486** [comment]
Ok, could you set it in the documentation ? thank you
