### ISSUE TITLE
Throw Error "Object reference not set to an instance of an object." on using MaterialMenuButton

### ISSUE THREAD

**Issue by TheAlphamerc** [contrix09/XF-Material-Library#120]
**Describe the bug**
When Using MaterialMenuButton on page it throw "Object reference not set to an instance of an object." on page loading 

**To Reproduce**
1.Add namespace in Xaml
` xmlns:material="clr-namespace:XF.Material.Forms.UI;assembly=XF.Material.Forms"`

2. Add below code on Xaml 
`<material:MaterialMenuButton ButtonType="Text" Grid.Row="1"    HorizontalOptions="End" Image="ic_overflow">
                    <material:MaterialMenuButton.Choices>
                        <x:Array Type="{x:Type x:String}">
                            <x:String>Add</x:String>
                            <x:String>Edit</x:String>
                            <x:String>Delete</x:String>
                        </x:Array>
                    </material:MaterialMenuButton.Choices>
                </material:MaterialMenuButton>`

3. Install app and run

**Debug Output**

> [MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.NullReferenceException: Object reference not set to an instance of an object.
[MonoDroid]   at XF.Material.Droid.MaterialHelper.get_DisplayMetrics () [0x00000] in /Users/vsts/agent/2.147.1/work/1/s/XF.Material/XF.Material.Droid/MaterialHelper.cs:20 
[MonoDroid]   at XF.Material.Droid.MaterialHelper.ConvertToDp (System.Double value) [0x00000] in /Users/vsts/agent/2.147.1/work/1/s/XF.Material/XF.Material.Droid/MaterialHelper.cs:24 
[MonoDroid]   at XF.Material.Droid.Renderers.MaterialDrawableHelper.UpdateCornerRadius () [0x00000] in /Users/vsts/agent/2.147.1/work/1/s/XF.Material/XF.Material.Droid/Renderers/MaterialDrawableHelper.cs:258 
[MonoDroid]   at XF.Material.Droid.Renderers.MaterialDrawableHelper..ctor (XF.Material.Forms.UI.IMaterialButtonControl button, Android.Views.View aView) [0x000ee] in /Users/vsts/agent/2.147.1/work/1/s/XF.Material/XF.Material.Droid/Renderers/MaterialDrawableHelper.cs:78 
[MonoDroid]   at XF.Material.Droid.Renderers.MaterialButtonRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x00049] in /Users/vsts/agent/2.147.1/work/1/s/XF.Material/XF.Material.Droid/Renderers/MaterialButtonRenderer.cs:38 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000c3] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:228 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:127 
[MonoDroid]   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:338 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:120 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:268 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:92 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:414 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000e0] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:231 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:127 
[MonoDroid]   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:338 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:120 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:268 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:92 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:414 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000e0] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:231 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:127 
[MonoDroid]   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:338 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:120 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:268 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:92 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:414 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000e0] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:231 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:127 
[MonoDroid]   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:338 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:120 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:268 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:92 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:414 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000e0] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:231 
[MonoDroid]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:127 
[MonoDroid]   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Support.V4.App.FragmentManager fragmentManager, Android.Content.Context context) [0x00031] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:385 
[MonoDroid]   at Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnCreateView (Android.Views.LayoutInflater inflater, Android.Views.ViewGroup container, Android.OS.Bundle savedInstanceState) [0x00008] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FragmentContainer.cs:56 
[MonoDroid]   at Android.Support.V4.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_inflater, System.IntPtr native_container, System.IntPtr native_savedInstanceState) [0x00020] in <96541ba8a6104b52aadf4218488f978c>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object.43(intptr,intptr,intptr,intptr,intptr)
[art] JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_throw'.
[Mono] Probing 'java_interop_jnienv_throw'.
[Mono] Found as 'java_interop_jnienv_throw'.
[MonoDroid] UNHANDLED EXCEPTION:
[Mono] Image addref System.Runtime.Serialization[0x96e2f3e0] -> System.Runtime.Serialization.dll[0x96f9f500]: 2
[Mono] Prepared to set up assembly 'System.Runtime.Serialization' (System.Runtime.Serialization.dll)
[Mono] Assembly System.Runtime.Serialization[0x96e2f3e0] added to domain RootDomain, ref_count=1
[Mono] AOT: image 'System.Runtime.Serialization.dll.so' not found: dlopen failed: library "/mnt/asec/com.kritivity.EventApp9-1/lib/arm/libaot-System.Runtime.Serialization.dll.so" not found
[Mono] AOT: image '/Users/builder/jenkins/workspace/xamarin-android-d15-9/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/lib/mono/aot-cache/arm/System.Runtime.Serialization.dll.so' not found: dlopen failed: library "/mnt/asec/com.kritivity.EventApp9-1/lib/arm/libaot-System.Runtime.Serialization.dll.so" not found
[Mono] Config attempting to parse: 'System.Runtime.Serialization.dll.config'.
[Mono] Config attempting to parse: '/Users/builder/jenkins/workspace/xamarin-android-d15-9/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/etc/mono/assemblies/System.Runtime.Serialization/System.Runtime.Serialization.config'.
[Mono] Assembly Ref addref Mono.Android[0xaa20f4c0] -> System.Runtime.Serialization[0x96e2f3e0]: 2
[Mono] Assembly Ref addref System.Runtime.Serialization[0x96e2f3e0] -> mscorlib[0xaa20d360]: 77
[MonoDroid] System.NullReferenceException: Object reference not set to an instance of an object.
[MonoDroid]   at (wrapper dynamic-method) System.Object.43(intptr,intptr,intptr,intptr,intptr)
[MonoDroid]   at (wrapper native-to-managed) System.Object.43(intptr,intptr,intptr,intptr,intptr)
[MonoDroid]   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_boolean_method_a(intptr,intptr&,intptr,intptr,Java.Interop.JniArgumentValue*)
[MonoDroid]   at Java.Interop.JniEnvironment+InstanceMethods.CallBooleanMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00053] in <da9f450baed342f3af31c42cec968688>:0 
[MonoDroid]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractBooleanMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <da9f450baed342f3af31c42cec968688>:0 
[MonoDroid]   at Android.Support.V4.App.FragmentManagerInvoker.ExecutePendingTransactions () [0x0000a] in <96541ba8a6104b52aadf4218488f978c>:0 
[MonoDroid]   at Xamarin.Forms.Platform.Android.FragmentManagerExtensions.ExecutePendingTransactionsEx (Android.Support.V4.App.FragmentManager fragmentTransaction) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\Extensions\FragmentManagerExtensions.cs:42 
[MonoDroid]   at Xamarin.Forms.Platform.Android.AppCompat.MasterDetailContainer.Dispose (System.Boolean disposing) [0x0004e] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\MasterDetailContainer.cs:142 
[MonoDroid]   at Java.Lang.Object.Dispose () [0x00000] in <5f142c269d8a438c94480ac03744dec7>:0 
[MonoDroid]   at Xamarin.Forms.Platform.Android.AppCompat.MasterDetailPageRenderer.Dispose (System.Boolean disposing) [0x00046] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\MasterDetailPageRenderer.cs:224 
[MonoDroid]   at Java.Lang.Object.Dispose () [0x00000] in <5f142c269d8a438c94480ac03744dec7>:0 
[MonoDroid]   at Xamarin.Forms.Platform.Android.AppCompat.Platform.Cleanup (System.Collections.Generic.List`1[T] viewsToRemove, System.Collections.Generic.List`1[T] renderersToDispose) [0x00036] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:338 
[MonoDroid]   at Xamarin.Forms.Platform.Android.AppCompat.Platform.SetPageInternal (Xamarin.Forms.Page newRoot) [0x000b9] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:322 
[MonoDroid]   at Xamarin.Forms.Platform.Android.AppCompat.Platform+<>c__DisplayClass36_0.<SetPage>b__0 () [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:269 
[MonoDroid]   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <5f142c269d8a438c94480ac03744dec7>:0 
[MonoDroid]   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <5f142c269d8a438c94480ac03744dec7>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object.33(intptr,intptr)
[mono-rt] Stacktrace:
[mono-rt] 
[mono-rt]   at <unknown> <0xffffffff>
[mono-rt]   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_new_string (intptr,intptr&,char*,int) <0x00043>
[mono-rt]   at Java.Interop.JniEnvironment/Strings.NewString (char*,int) [0x00009] in <da9f450baed342f3af31c42cec968688>:0
[mono-rt]   at Java.Interop.JniEnvironment/Strings.NewString (string) [0x00024] in <da9f450baed342f3af31c42cec968688>:0
[mono-rt]   at Android.Runtime.JNIEnv.NewString (string) [0x0000a] in <5f142c269d8a438c94480ac03744dec7>:0
[mono-rt]   at Java.Lang.Error..ctor (string) [0x00020] in <5f142c269d8a438c94480ac03744dec7>:0
[mono-rt]   at Android.Runtime.JavaProxyThrowable..ctor (System.Exception) [0x00007] in <5f142c269d8a438c94480ac03744dec7>:0
[mono-rt]   at Java.Lang.Throwable.FromException (System.Exception) [0x0001e] in <5f142c269d8a438c94480ac03744dec7>:0
[mono-rt]   at Android.Runtime.AndroidEnvironment.UnhandledException (System.Exception) [0x0006a] in <5f142c269d8a438c94480ac03744dec7>:0
[mono-rt]   at (wrapper dynamic-method) object.33 (intptr,intptr) [0x00029] in <d4a23bbd2f544c30a48c44dd622ce09f>:0
[mono-rt]   at (wrapper native-to-managed) object.33 (intptr,intptr) [0x00021] in <d4a23bbd2f544c30a48c44dd622ce09f>:0

> 

**Expected behavior**
It Should show menu as displayed in project documentation.

**Version Used:**
 - Xamarin.forms: [3.6.0]
 - XF.Material: [1.4.1.1]

**Comment by TheAlphamerc** [comment]
**Problem Solved**

I just forget to initilised
`XF.Material.Droid.Material.Init(this, bundle);`
in Android plateform

**Comment by contrix09** [comment]
Lol I was just about to say that.
