### ISSUE TITLE
Reference to Lottie.Android

### ISSUE THREAD

**Issue by JPetronilhoNunes** [contrix09/XF-Material-Library#13]
**Describe the bug**
When trying to compile project an error appear:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Can not resolve reference: `Lottie.Android`, referenced by `XF.Material.Droid`. Please add a NuGet package or assembly reference for `Lottie.Android`, or remove the reference to `XF.Material.Droid`.	
I already referenced Com.Airbnb.Xamarin.Forms.Lottie and the error constinues.

**To Reproduce**
Compile project with XF-Material-Library added

![capturar](https://user-images.githubusercontent.com/42891240/47151274-2ffe6880-d2d1-11e8-80aa-09a680e4770b.PNG)

**Desktop (please complete the following information):**
 - OS: android xamarin forms

**Comment by contrix09** [comment]
Hi, maybe there are conflicting package referenced by other nuget packages that is lower than the version of the references of XF.Material library?

Is the error above from the nuget package manager?

Can you also provide the versions of each nuget packages that you used in the Android project, so I can cross-reference them and see if there are any conflicting references.

**Comment by JPetronilhoNunes** [comment]
> Hi, maybe there are conflicting package referenced by other nuget packages that is lower than the version of the references of XF.Material library?
> 
> Is the error above from the nuget package manager?
> 
> Can you also provide the versions of each nuget packages that you used in the Android project, so I can cross-reference them and see if there are any conflicting references.

Many thanks for your reply, here is my android.csproj file, which contains all references and respective versions:

<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{24CE3C36-16B9-426D-AA0C-5961ECF8D88C}</ProjectGuid>
    <ProjectTypeGuids>{EFBA0AD7-5A72-4C68-AF49-83D382785DCF};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    <TemplateGuid>{9AA2D3C6-3393-45F1-8E7C-5A9901728795}</TemplateGuid>
    <OutputType>Library</OutputType>
    <RootNamespace>CAVCMobU.Droid</RootNamespace>
    <AssemblyName>CAVCMobU.Android</AssemblyName>
    <AndroidApplication>True</AndroidApplication>
    <AndroidResgenFile>Resources\Resource.designer.cs</AndroidResgenFile>
    <AndroidResgenClass>Resource</AndroidResgenClass>
    <AndroidManifest>Properties\AndroidManifest.xml</AndroidManifest>
    <MonoAndroidResourcePrefix>Resources</MonoAndroidResourcePrefix>
    <MonoAndroidAssetsPrefix>Assets</MonoAndroidAssetsPrefix>
    <AndroidUseLatestPlatformSdk>false</AndroidUseLatestPlatformSdk>
    <TargetFrameworkVersion>v7.1</TargetFrameworkVersion>
    <AndroidHttpClientHandlerType>Xamarin.Android.Net.AndroidClientHandler</AndroidHttpClientHandlerType>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug</OutputPath>
    <DefineConstants>DEBUG;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidLinkMode>None</AndroidLinkMode>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidManagedSymbols>true</AndroidManagedSymbols>
    <AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Android" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Acr.UserDialogs">
      <Version>7.0.1</Version>
    </PackageReference>
    <PackageReference Include="Com.Airbnb.Xamarin.Forms.Lottie">
      <Version>2.6.3</Version>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json">
      <Version>11.0.2</Version>
    </PackageReference>
    <PackageReference Include="Rg.Plugins.Popup">
      <Version>1.1.4.168</Version>
    </PackageReference>
    <PackageReference Include="sqlite-net-pcl">
      <Version>1.5.231</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.Connectivity">
      <Version>3.2.0</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.DeviceInfo">
      <Version>4.0.0.13</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms" Version="3.2.0.871581" />
    <PackageReference Include="Xamarin.Android.Support.Design" Version="25.4.0.2" />
    <PackageReference Include="Xamarin.Android.Support.v7.AppCompat" Version="25.4.0.2" />
    <PackageReference Include="Xamarin.Android.Support.v4" Version="25.4.0.2" />
    <PackageReference Include="Xamarin.Android.Support.v7.CardView" Version="25.4.0.2" />
    <PackageReference Include="Xamarin.Android.Support.v7.MediaRouter" Version="25.4.0.2" />
    <PackageReference Include="XF.Material">
      <Version>1.1.1</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="MainActivity.cs" />
    <Compile Include="Remote\Remote.cs" />
    <Compile Include="Remote\RemoteBase.cs" />
    <Compile Include="Resources\Resource.Designer.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <AndroidAsset Include="Assets\Font Awesome 5 Free-Regular-400.otf" />
    <None Include="Resources\AboutResources.txt" />
    <None Include="Assets\AboutAssets.txt" />
    <None Include="Properties\AndroidManifest.xml" />
  </ItemGroup>
  <ItemGroup>
    <AndroidResource Include="Resources\layout\Tabbar.axml" />
    <AndroidResource Include="Resources\layout\Toolbar.axml" />
    <AndroidResource Include="Resources\values\styles.xml" />
    <AndroidResource Include="Resources\values\colors.xml" />
    <AndroidResource Include="Resources\mipmap-anydpi-v26\icon.xml" />
    <AndroidResource Include="Resources\mipmap-anydpi-v26\icon_round.xml" />
    <AndroidResource Include="Resources\mipmap-hdpi\Icon.png" />
    <AndroidResource Include="Resources\mipmap-hdpi\launcher_foreground.png" />
    <AndroidResource Include="Resources\mipmap-mdpi\Icon.png" />
    <AndroidResource Include="Resources\mipmap-mdpi\launcher_foreground.png" />
    <AndroidResource Include="Resources\mipmap-xhdpi\Icon.png" />
    <AndroidResource Include="Resources\mipmap-xhdpi\launcher_foreground.png" />
    <AndroidResource Include="Resources\mipmap-xxhdpi\Icon.png" />
    <AndroidResource Include="Resources\mipmap-xxhdpi\launcher_foreground.png" />
    <AndroidResource Include="Resources\mipmap-xxxhdpi\Icon.png" />
    <AndroidResource Include="Resources\mipmap-xxxhdpi\launcher_foreground.png" />
    <AndroidResource Include="Resources\drawable\xamarin_logo.png" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Resources\drawable-hdpi\" />
    <Folder Include="Resources\drawable-xhdpi\" />
    <Folder Include="Resources\drawable-xxhdpi\" />
    <Folder Include="Resources\drawable-xxxhdpi\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\bms.mobile.framework\Utils\Utils\Utils.csproj">
      <Project>{67f9d3a8-f71e-4428-913f-c37ae82cdb24}</Project>
      <Name>Utils</Name>
    </ProjectReference>
    <ProjectReference Include="..\CAVCMobU\CAVCMobU.csproj">
      <Project>{AC0CAD39-C91A-4083-89C7-4ADDA73754BC}</Project>
      <Name>CAVCMobU</Name>
    </ProjectReference>
  </ItemGroup>
  <Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets" />
</Project>

**Comment by contrix09** [comment]
try to update your `Xamarin.Android.Support.*` packages to `27.0.2.*` and see if it fixes the issue. `Com.Airbnb.Xamarin.Forms.Lottie` version `2.5.4` or above requires `Xamarin.Android.Support.*` at least `27.0.2.*`. It turns out I have inconsistencies to the required referenced Nuget packages in my nuspec file.

**Comment by JPetronilhoNunes** [comment]
Many thanks, that was it! I can compile now.
