### ISSUE TITLE
Typography not work 

### ISSUE THREAD

**Issue by breakcoding** [contrix09/XF-Material-Library#132]
I have problem in version 1.4.1 with "Typography", I had the Fonts in Android and iOS but when I debug there is not changes with, I used this line to define the "Typography" is correct?:

`<Label
                        Text="xxx"
                        Style="{DynamicResource Material.TypeScale.H4}" />`

**Comment by thiagoparabas** [comment]
Man, using MaterialLabel with TypeScale.

![image](https://user-images.githubusercontent.com/47533199/55024180-1f1ef500-4fdd-11e9-94d9-5b9c3b3a9798.png)

**Comment by breakcoding** [comment]
> Man, using MaterialLabel with TypeScale.
> 
> ![image](https://user-images.githubusercontent.com/47533199/55024180-1f1ef500-4fdd-11e9-94d9-5b9c3b3a9798.png)

Thanks!!!
