### ISSUE TITLE
Exception on calling XF.Material.Forms.Material.Init(this) on App()

### ISSUE THREAD

**Issue by JPetronilhoNunes** [contrix09/XF-Material-Library#14]
**Describe the bug**
As stated in your explanation I've put XF.Material.Forms.Material.Init(this) on the App constructor, as depited on the attached image. When the execution point hits this line an exception reportung a NullReferenceError popsup.

**To Reproduce**
Install all the packages and setup as explained, then execute app

**Expected behavior**
Should continue execution as expected.

**Screenshots**
![capturar](https://user-images.githubusercontent.com/42891240/47221109-7cb67200-d3ab-11e8-8fb6-40962069f8f5.PNG)

**Desktop (please complete the following information):**
 - OS: Xamarin Forms 3.2 

**Smartphone (please complete the following information):**
  Android Emulator with onreo 8.1 installed

**Additional context**
This are all my pcakges installed and respective versions

**Comment by JPetronilhoNunes** [comment]
My mistake, I should call it passing the resource sytle name.

**Comment by tscholze** [comment]
@JPetronilhoNunes I get the same error. Could you please tell me, what do you meant with the `resource style name`? Thanks for helping!

**Comment by contrix09** [comment]
@tscholze What version are you using? This has already been resolved since `1.1.2`. If you are using an older version, you can refer to [this](https://github.com/contrix09/XF-Material-Library#adding-the-material-resources).

**Comment by tscholze** [comment]
@contrix09 After cleaning up and dating up all the Xamarin Form packages (this is my very first Xamarin App) - everything seems to work fine!

You build a great library!
