### ISSUE TITLE
Input Dialog Request

### ISSUE THREAD

**Issue by alexrysgspr** [contrix09/XF-Material-Library#18]
Hi sir. Can you also implement an input dialog like this?
[](https://ibb.co/jEC0O0)

An input dialog that accepts input when confirmed.
I've tried ACR.userdialog's prompt but it's kinda hard to customize.
[](https://github.com/aritchie/userdialogs/blob/master/docs/prompt.md)

**Comment by contrix09** [comment]
Hi, I am planning to implement this feature but maybe in version 1.3. I am still fixing some minor bugs and will release version 1.1.2. For now, I will re-open this issue as a feature request.
