### ISSUE TITLE
checkbox doesn't show on ios

### ISSUE THREAD

**Issue by muhammetsahin** [contrix09/XF-Material-Library#186]
## 🐛 Bug Report

Checkbox doesnt work on ios 13 but android works fine.
Xamarin.Forms version: 4.2.0.84xxx

Application debug window i saw this message
"Image loading failed: xf_checkbox_selected
System.IO.FileNotFoundException: xf_checkbox_selected"
"Image loading failed: xf_checkbox_unselected
System.IO.FileNotFoundException: xf_checkbox_unselected"

<img width="308" alt="Ekran Resmi 2019-10-04 23 54 14" src="https://user-images.githubusercontent.com/2045788/66239376-5e539e80-e702-11e9-9061-da4adf0a2e23.png">

### Expected behavior
ios should show checkbox
### Configuration

**Version:** 1.5.1

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by dimiszk** [comment]
Same problem on IOS

The problem occurs and on radio buttons.

XF.Material 1.5.1
Xamarin.Forms 4.2.0.848062

![error](https://user-images.githubusercontent.com/11929666/66252542-b40d6280-e765-11e9-8514-bd3a209a7d51.png)

**Comment by muhammetsahin** [comment]
i solved by myself.

Here is the solution:

Add missing image to the ios project.

![image](https://user-images.githubusercontent.com/2045788/66254867-22155200-e785-11e9-8538-e6f4a30b75ee.png)

But I still think it's a bug.

**Comment by martijn00** [comment]
This should be fixed in this commit: https://github.com/BaseflowIT/XF-Material-Library/commit/97bb58e111b2a68eacdb8b80984c08ac46a8cfeb

Let me know if this works when 1.5.2 is released.

**Comment by fjorge-joshkautz** [comment]
I can't speak for everyone, but I updated to 1.5.2 this morning and I do not see the radio buttons on the simulator running iOS 13.0.


 I'll attach a video to [demonstrate this behavior](https://i.imgur.com/iOjkCqV.mp4).

**Comment by fjorge-joshkautz** [comment]
Furthermore, in the Android emulator, there is some peculiar behavior:
The first selection becomes unchangeable, and then you are able to select any other options you want. I noticed this behavior in Android API 28 and 29, and have not tested in earlier releases.

XAML:
```
<material:MaterialRadioButtonGroup 
     x:Name="Test"
     BackgroundColor="Aqua"
     SelectedColor="Red"
     TextColor="Green"
     UnselectedColor="Yellow"/>
```

C#:
```
Test.Choices = new List<String> {"One", "Two", "Three", "Four"};
```

I'll attach a video to [demonstrate this behavior](https://i.imgur.com/ratp59e.mp4).

**Comment by martijn00** [comment]
@fjorge-joshkautz can you open a PR to showcase this in the MaterialMvvmSample that is in this repo?

**Comment by fjorge-joshkautz** [comment]
Hey there @martijn00 I tried it in the MaterialMvvmSample, and did not have any issues - so that tells me that it's something I don't have set up right. I'll look into it further. Thanks for checking, and I apologize for the false alarm!

**Comment by fjorge-joshkautz** [comment]
I just created a brand new Xamarin Forms project from scratch, added XF.Material library, and included a material:MaterialRadioButtonGroup element on the MainPage, and get the same errors I mentioned previously.

**Comment by Miiite** [comment]
I had the same issue with the MaterialLoadingView, which just doesn't show up on iOS. From looking at the source code it looks like the lottie json file is not properly included in the iOS package upon build. I'll have to test that again with 1.5.2

**Comment by martijn00** [comment]
I've released 1.5.4. Does this fix it?

**Comment by joshkautz** [comment]
I'm afraid not yet, for me at least.

iOS: no radio button images render to the screen
![Simulator Screen Shot - iPhone 11 Pro - 2019-10-18 at 08 01 36](https://user-images.githubusercontent.com/17554471/67096342-8e2c8880-f17d-11e9-902f-67f1639ae882.png)

Android: radio button images render to the screen, but multiple radio buttons can be chosen, and the initial choice cannot be unchosen.
![73541641_504747597032631_7784032348827287552_n](https://user-images.githubusercontent.com/17554471/67096494-f7140080-f17d-11e9-8a7a-430de84ef35a.jpg)

**Comment by balaji830** [comment]
Thanks to muhammetsahin. I did the same by copying the required images to resources folder in IOS project.

**Comment by OdetteP** [comment]
Did the commit fix the issue?

**Comment by klemmchr** [comment]
And when will the fix be released? This library is essentially broken for iOS as none of the assets is showing up there. Neither loading spinners, checkboxes and so on.
