### ISSUE TITLE
Input Dialog

### ISSUE THREAD

**Issue by alexrysgspr** [contrix09/XF-Material-Library#19]
Hi sir. Can you also implement an input dialog like this?
[](https://ibb.co/jEC0O0)

An input dialog that accepts input when confirmed.
I've tried ACR.userdialog's prompt but it's kinda hard to customize.
[](https://github.com/aritchie/userdialogs/blob/master/docs/prompt.md)

**Comment by contrix09** [comment]
Hi, I am planning to implement this, but it will be released may be in version 1.3. Right now I'm working on minor bug fixes for version 1.1.2. For now, I'm going to re-open this as a feature request. I'll keep you updated by tracking this issue.

**Comment by alexrysgspr** [comment]
Sorry for the spam. Btw, thanks!
