### ISSUE TITLE
MaterialCircularLoadingView doesn't appear anymore on iOS

### ISSUE THREAD

**Issue by AndreMassa997** [contrix09/XF-Material-Library#195]
## 🐛 Bug Report

After update 1.5.0 the standard MaterialCircularLoadingView and the CircularLoadingView in the LoadingDialogAsync (see the screenshot attached) doesn't appear anymore it seems to be transparent but I set the TintColor. 
In Android it works perfectly. 

I tried with iOS 12.4 and 13.1.

![IMG_0130](https://user-images.githubusercontent.com/56446608/66664598-1d511200-ec4d-11e9-8c14-50750e7fb97e.png)

Thanks for the support!

**Comment by CodeOfDarkness** [comment]
Same error in my project. Is there already any workaround to get the progress indicator visible again?

**Comment by Miiite** [comment]
@AndreMassa997 @CodeOfDarkness It's being investigated, and a PR is open to try to fix this 
https://github.com/BaseflowIT/XF-Material-Library/pull/197

In the meantime, stick to version < 1.5.0 if you can.

**Comment by AndreMassa997** [comment]
@Miiite Thanks for the response, I can't return to version <1.5.0 because it doesn't work with iOS 13, I wait for a new release.
Thanks a lot!

**Comment by CodeOfDarkness** [comment]
@Miiite Thank you very much for the quick PR. 
It's the same for me, I also can't return to version < 1.5.0 because of iOS13.
I will wait for next release, too.

**Comment by martijn00** [comment]
I've released 1.5.4. Does this fix it?

**Comment by AndreMassa997** [comment]
@martijn00 No, unfortunately it's the same with version 1.5.4

**Comment by CodeOfDarkness** [comment]
@martijn00 Same for me.

**Comment by mtsrdr** [comment]
@martijn00 

I cloned the repository and manually edited the XF.Material.csproj file and it seems to be working for me:

  <ItemGroup Condition=" $(TargetFramework.StartsWith('xamarin.ios')) ">
    <None Remove="Platforms\Apple\**\*.cs" />
    <None Remove="Platforms\Ios\**\*.cs" />
    <None Remove="Platforms\Xamarin\**\*.cs" /> 
    <None Remove="Resources\*.png" />
    <None Remove="Resources\*.json" />
    <Compile Include="Platforms\Apple\**\*.cs" />
    <Compile Include="Platforms\Ios\**\*.cs" />
    <Compile Include="Platforms\Xamarin\**\*.cs" />
    <BundleResource Include="Resources\*.png" />
    <BundleResource Include="Resources\*.json" />
    <None Include="Info.plist" />
  </ItemGroup>

I first removed the BundleResource files and added them again, which prevented them from being duplicated in Visual Studio.

I don't know if this is a good solution, but it's working.

![Simulator Screen Shot - iPhone 11 Pro - 2019-10-18 at 16 38 33](https://user-images.githubusercontent.com/33626789/67123131-cf488b00-f1c5-11e9-8cc8-9ff33ca1f976.png)
![Simulator Screen Shot - iPhone 11 Pro - 2019-10-18 at 16 38 19](https://user-images.githubusercontent.com/33626789/67123132-cf488b00-f1c5-11e9-91c0-177135e910f4.png)

**Comment by OdetteP** [comment]
Did the commit fix the issue?

**Comment by shubhamkumarnayak** [comment]
> Did the commit fix the issue?

It is working now, thank you.

**Comment by MarManiak** [comment]
This error seems to have re-appeared.  I am running the latest version 1.7.5 on IOS14.  When I run the app on my mac in the simulator, it give an error about "Animation not found" when displaying the loading dialog.

**Comment by gimenezfrg** [comment]
The same here, the animation does not appear. Version 1.7.5

**Comment by robertkemp** [comment]
I just started testing LoadingDialog (XF-Material-Library 1.7.5, iOS 14.1) in my app and am also seeing the `+[LOTComposition animationNamed:inBundle:]: Animation Not Found` message when loading the dialog.

**Comment by alextorres50** [comment]
The same here, the animation does not appear. Version 1.8.0, reopen this bug please...
