### ISSUE TITLE
IsAutoCapitalizationEnabled is not working in MaterialTextField

### ISSUE THREAD

**Issue by Maurya2012Abhishek** [contrix09/XF-Material-Library#196]
## 🐛 Bug Report

IsAutoCapitalizationEnabled = true is not working in MaterialTextField. Only first latter of Keyboard is Capital latter as soon as an entering second word it is coming in small latter.

### Expected behavior

All latter should Enter in Capital latter when  IsAutoCapitalizationEnabled = true.

### Configuration

**Version:** 1.4.1.3

**Platform:** 
- [x] :iphone: iOS did't check
- [x] :robot: Android

**Comment by Miiite** [comment]
It's not a bug, this is how the feature is supposed to work.
What you are looking for is a way to have the text in all caps, like the Android attribute android:textAllCaps.

So to be clear IsAutoCapitalisationEnabled is working fine.
