### ISSUE TITLE
Unable to set Xaml Global style in App.xaml

### ISSUE THREAD

**Issue by ShahmanTeh** [contrix09/XF-Material-Library#20]
Hi, I was unable to set any Xamarin.Forms `<style>` tag for any Material Components. Setting the `<style>` in specific page is working, but not global styles.

**Comment by contrix09** [comment]
Can I see your xaml file for setting global styles?

**Comment by contrix09** [comment]
I will close this issue for now.

**Comment by muhammet-mucahit** [comment]
Hey I have the same problem in my code.

This is my Global Style in App.xaml:

<Style TargetType="material:MaterialTextField">
                <Setter Property="TextFontSize" Value="20" />
                <Setter Property="HeightRequest" Value="60" />
                <Setter Property="TextFontFamily" Value="{DynamicResource Font}" />
                <Setter Property="PlaceholderFontFamily" Value="{DynamicResource Font}" />
                <Setter Property="TintColor" Value="{DynamicResource Secondary}" />
</Style>

Through this, I want all of my MaterialTextFields to derive this style.

For example in Xamarin Items, it is working.
<Style TargetType="Entry">
                <Setter Property="FontSize" Value="20" />
                <Setter Property="HeightRequest" Value="50" />
                <Setter Property="FontFamily" Value="{StaticResource Font}" />
                <Setter Property="TextColor" Value="{StaticResource OnSurface}" />
</Style>

If I give key to my style and call that key in every MaterialTextField, it is working but I don't like it. Can you help me about that? Thanks

**Comment by contrix09** [comment]
Can you provide the complete XAML style for the text field?
