### ISSUE TITLE
StaticResource Material.Dialog.Width is missing

### ISSUE THREAD

**Issue by NPadrutt** [contrix09/XF-Material-Library#206]
## 🐛 Bug Report

I added the library to an existing project (https://github.com/MoneyFox/MoneyFox).
When I call the following code from the samples 
```
            await MaterialDialog.Instance.ConfirmAsync(message: "Do you want to sign in?",
                                                       confirmingText: "Sign In");
```

I get this Exception:

```
Xamarin.Forms.Xaml.XamlParseException: 'Position 19:32. StaticResource not found for key Material.Dialog.Width'
```
I have Xamarin.Forms and Xamarin.Forms.Visual.Material 4.3.908675. 
So far it only happens in my existing project. In newly created one it works. I thought that there might be a conflicht with Xamarin.Forms.Visual.Material. But the issue persists when I remove the package.
As far as I can see I followed the getting started guide. Any idea what causes this?

### Expected behavior
The Dialog opens.

### Configuration

**Version:** 1.5.4

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android 
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

Target Android Version: Q
Emulator Android: P

**Comment by OdetteP** [comment]
I tried to reproduce but could not find the error that you are getting. Do you have some more code to show? Or maybe check 'Position 19:32 where the error is found

**Comment by NPadrutt** [comment]
So far I couldn't reproduce it in a sample as well, just in my project here. But it seems like there are most of the Resources missing in a way. For example when I just add a button:

                <ui:MaterialButton Text="test" />

I get the excpetion: 

                **System.InvalidOperationException:** 'Invalid on Color.Default'

I'll happy to share any code. What would be helpful?
As to the Position, I assume that this is referencing to the XAML of the dialog in the library.

**Comment by OdetteP** [comment]
Can you please showcase this in an PR by adding it to the MaterialMvvmSample in this repo?

**Comment by NPadrutt** [comment]
So far I can't really. I tried to create a minimal viable example, but in these examples it is always working. I hoped you can give me a hint on what could be the problem so I can get an example working or can fix the issue in my project.

**Comment by garyng** [comment]
@NPadrutt Try clone and import the library locally before debugging so that you can step through both your code and this library's code - it might be specific to your use case. I used this method to haunt down some very rare/specific NRE (that is related to this library) in my project though.

_PS: maybe integrate [GitLink](https://github.com/GitTools/GitLink) to ease the process?_

**Comment by NPadrutt** [comment]
@garyng: good idea. I will try that as soon as I have some time.  Thanks.

**Comment by dustincatap** [comment]
I checked your code and you have this class `ThemeManager`. When the theme is changed, it removes all merged dictionaries and re-adds them according to the new theme config.

```c#
public static void ChangeTheme(AppTheme theme)
{
    ICollection<ResourceDictionary> mergedDictionaries = Xamarin.Forms.Application.Current.Resources.MergedDictionaries;
    if (mergedDictionaries != null)
    {
        mergedDictionaries.Clear();

        ...
    }
}
```

`XF.Material.Forms.Init()` merges the library's own resources to your current. I guess when you change/update your theme, the library's resources are removed and thus will result to the `StaticResource not found` error when showing a dialog.

**Comment by NPadrutt** [comment]
Oh, you're absolutely right. I should have thought about that one. Thank you very much! :)

**Comment by yankarinRG** [comment]
I was having the same problem. I forgot to add `XF.Material.Forms.Material.Init(this);` to Xamarin Form's App constructor after `InitializeComponent();`.
