### ISSUE TITLE
Border Textfield appear and background=Transparent and TintColor doesnt work 

### ISSUE THREAD

**Issue by alextorres50** [contrix09/XF-Material-Library#218]
### Old (and correct) behavior
The textfield doesn't  show the border of UITextfield on IOs 
![IMG_20191108_154252](https://user-images.githubusercontent.com/26494805/68509357-bec48700-023e-11ea-93da-72a45185db8c.jpg)

### Current behavior
The textfield  show the border of uitextfield on IOs and the background has a fill white color when the property Background = Transparent 

![IMG_20191108_153247](https://user-images.githubusercontent.com/26494805/68508827-693baa80-023d-11ea-82af-3f44332580fa.jpg)

### Reproduction steps
since X.F Material 1.5.0 doesn't works, update my nuget reference since XF. Material 1.4.1.3 

### Configuration
Xamarin.Forms 4.3.0. 9747036

**Version:** since 1.5.0 and newest

**Platform:** 
- [ X] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ X] :monkey: Xamarin.Forms

**Comment by OdetteP** [comment]
Is this solved with the updated version 1.5.8

**Comment by alextorres50** [comment]
No, the bug remains the same

**Comment by alextorres50** [comment]
yes, this version solved the bug
