### ISSUE TITLE
MaterialCheckbox text get truncated from the tail.

### ISSUE THREAD

**Issue by tp16190** [contrix09/XF-Material-Library#22]
MaterialCheckbox text get truncated from the tail when text description is large. It will wrap the text so all text will display. See below image for reference

![chk1](https://user-images.githubusercontent.com/8983699/47503413-aed24300-d887-11e8-9f17-985d8bb91d1b.png)

**Comment by contrix09** [comment]
Hi, for now I can't change the layouting behavior of `MaterialCheckbox`. The`BaseSelectionControl` view, which all selection control derives from, has a fixed height of 48 units. Both icon and text are vertically aligned `Center`, changing them to `Start` will cause a misalignment among them.

For now I recommend you use a `MaterialCheckbox` without `Text` property. Then use a `Label` for the text. Place both in a layout, either in a `Grid` or `StackLayout`. Here is an example:

```xml
<StackLayout Orientation="Horizontal">
     <material:MaterialCheckbox IsSelected="{Binding AcceptedTerms}" />
     <Label Margin="0,12,0,0" Text="By accepting our license terms, you allow Lorem Ipsum Company to 
     collect anonymous data and send them to our servers." />
</StackLayout>
```

![image](https://user-images.githubusercontent.com/29834445/47536173-59cb1700-d8f1-11e8-89e4-23839af7cd5d.png)

You can adjust the `Margin` of the `Label` to align it with the `MaterialCheckbox`.

**Comment by tp16190** [comment]
thanks.. this will solve my problem...
