### ISSUE TITLE
Error occurred while running app iOS App. Error **Foundation.MonoTouchException:**  

### ISSUE THREAD

**Issue by manonaga2188** [contrix09/XF-Material-Library#221]
## 🐛 Bug Report

 XFMaterialSample.iOS[783:315076] *** Assertion failure in -[UIApplication _createStatusBarWithRequestedStyle:orientation:hidden:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3900.12.15/UIApplication.m:5316
Thread started:  #3
**Foundation.MonoTouchException:** 'Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.

### Configuration

**Version:** 1.x
Xcode = 11.2.1
iPhone 6s
Visual Studio Community Edition 2019  Version 16.3.9
**Platform:** 
- [x] :iphone: iOS

**Comment by OdetteP** [comment]
This is the same as #225. Please follow the status there.

**Comment by manonaga2188** [comment]
@OdetteP  I installed wrong nuget package(**XF.Material.Custom**) instead of **XF.Material**

I'm confirming this is not an issue. 
Now working fine with correct package
