### ISSUE TITLE
[IOS] MaterialButton ImageSource showing black box instead of the image.

### ISSUE THREAD

**Issue by Laelius** [contrix09/XF-Material-Library#222]
## 🔙 Regression
It was working before, I could setup any ImageSource and it would accept it. Now it shows a black box. This problem only happens on iOS, works fine in android.

**Version:** 1.5.4

**Platform:** 
- [ x ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by OdetteP** [comment]
Can you please add some code or add it to the sample in public github repo

**Comment by Laelius** [comment]
`<material:MaterialButton Text="Test Sample" FontSize="16" ImageSource="button_ADD_blue.png" BackgroundColor="Transparent"
                                                          FontFamily="{DynamicResource NormalFont}"  TextColor="#000000" AllCaps="False" LetterSpacing="0"
                                                         Command="{Binding ClickTesteCommand}" HorizontalOptions="Start" Margin="-15,0,0,0">
                        </material:MaterialButton>`

**Comment by Laelius** [comment]
Any new followup on this?

**Comment by OdetteP** [comment]
I replicated it with your code and it works fine for me.  Do you have the ImageSource in both Android and iOS project?
