### ISSUE TITLE
Application not working in iOS 13.2 on simulator

### ISSUE THREAD

**Issue by shubhambhosale** [contrix09/XF-Material-Library#225]
Hi, 
I am trying to build the application on latest iOS version 13.2. I am getting an exception as 
"Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.". After this application crashes.

I am not sure, It is working with iOS 12. 
I have tried to install same on the device which has iOS version 13.2 installed, It is working fine on it.

**Comment by OdetteP** [comment]
I tried to replicate the error but so far I did not get any error or crashes. Can you help me out and please recreate the error in the sample code in the public github repo.

**Comment by shubhambhosale** [comment]
Thanks for the reply. 
I am able to resolve the issue after upgrading the Xamarin Forms & XF.Material to the latest version. 
Old Versions:
Xamarin.Forms Version="3.6.0.709228"
XF.Material Version="1.4.1.3".
With this old versions my project is works in actual devices. But when I have tried to debug in simulator it gives me an above mentioned error. I am not sure why this is happening.
