### ISSUE TITLE
Default selected choice is not working in MaterialTextField

### ISSUE THREAD

**Issue by manonaga2188** [contrix09/XF-Material-Library#226]
## 🐛 Bug Report

<material:MaterialTextField x:Name="txtPicker" FloatingPlaceholderEnabled="False" HelperText="Sample Tooltip" ErrorText="Invalid Input" InputType="Choice" ShouldAnimateUnderline="True" HasError="False" LeadingIcon="battery.png" PlaceholderColor="Transparent"  Choices="{Binding Jobs}" Text="Web Developer" SelectedChoice="Web Developer" />

### Expected behavior
When choices popup open, Initial Web Developer option should be selected.

**Comment by OdetteP** [comment]
Can you please add the code to the sample code of this library and make a PR and I will have a look.

**Comment by manonaga2188** [comment]
@OdetteP  Sure

**Comment by manonaga2188** [comment]
@OdetteP  I'm Not able to create PR. Here is code..
In MaterialTextFieldView.xaml File, Add new control.
` <material:MaterialTextField FloatingPlaceholderEnabled="False" HelperText="Sample Tooltip" ErrorText="Invalid Input" InputType="Choice" ShouldAnimateUnderline="True" HasError="False" PlaceholderColor="Transparent"  Choices="{Binding Jobs}" SelectedChoice="Web Developer" Text="Web Developer"/>`

In **MaterialTextFieldView.xaml.cs** File, BindingContext is changed to MaterialTextFieldViewModel.
```
 public MaterialTextFieldView()
        {
            InitializeComponent();
            BindingContext = new MaterialTextFieldViewModel();
        }
```

**MaterialTextFieldViewModel Page**
```
public class MaterialTextFieldViewModel : BaseViewModel
    {
        ObservableCollection<string> jobs;
        public ObservableCollection<string> Jobs { get => jobs; set { jobs = value; OnPropertyChanged(); } }
        public MaterialTextFieldViewModel()
        {
            Jobs = new ObservableCollection<string>() {
            "Mobile Developement(Xamarin)",
            "Mobile Developement(Native)",
            "Web Developer",
            "Web Developer(Laravel)",
            "Quality Engineer",
            "Business Analyst",
                "HR Manager(Process)",
            "Project Manager"
            };
        }
    }
```


That all I have added. I'm tried to set default value to choices which is not working correctly. 

Thank you,

**Comment by OdetteP** [comment]
I tried you code and in my case it is showing  "Web Developer" in MaterialTextField. So it works normal

**Comment by manonaga2188** [comment]
@OdetteP  Is my correct?.
I'm using Xamarin form 4.3. Can you check with 4.3 Xamarin version?

**Comment by manonaga2188** [comment]
https://github.com/manonaga2188/XFMaterialSample
