### ISSUE TITLE
Not able to change MaterialButton text in iOS. Works fine in Android

### ISSUE THREAD

**Issue by manonaga2188** [contrix09/XF-Material-Library#228]
## 🐛 Bug Report

 MaterialButton btn = new MaterialButton { 
            Text="Welcome"
            };
            btn.Clicked += Btn_Clicked;
            stContainer.Children.Add(btn);
private void Btn_Clicked(object sender, EventArgs e)
        {
            ((MaterialButton)sender).Text = "Clicked 1 TIme";
        }

Foundation.MonoTouchException: 'Objective-C exception thrown.  Name: NSRangeException Reason: NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds

### Configuration

**Version:** 1.x

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by OdetteP** [comment]
I added a sample where it works fine for iOS and Android.

**Comment by manonaga2188** [comment]
@OdetteP  Actually this problem occurs only in Xamatrin Form 4.3.0.991211

**Comment by manonaga2188** [comment]
> I added a sample where it works fine for iOS and Android.

@OdetteP Actually this problem occurs only in Xamatrin Form 4.3.0.991211

**Comment by andy200486** [comment]
I have the same problem, is there a version that fixes the bug ?
