### ISSUE TITLE
Display Snackbar above persistent footer elements

### ISSUE THREAD

**Issue by eceowl** [contrix09/XF-Material-Library#23]
When using the Snackbar with a bottom tabbed page on Xamarin forms, it is displayed on top of the navigation bar.  According to Material Design, the Snackbar should float above the navigation bar, as seen [here](https://material.io/design/components/snackbars.html#placement).

I'm not sure how feasible this is, but it would be a great feature, considering Xamarin forms just added support for bottom tabbed pages on Android.  

Thanks!

**Comment by contrix09** [comment]
Hi, I can add a `double` property in `MaterialSnackbarConfiguration` that can be used for offsetting the Snackbar above such elements.

**Comment by eceowl** [comment]
Cool, I was thinking that would probably be the simplest solution.

**Comment by contrix09** [comment]
For future references, the property `BottomOffset` will be removed in version `1.4.1.0`. You can use the property `Margin` for adjusting the thickness of both sides of the snackbar from the screen.
