### ISSUE TITLE
Can't build on iOS

### ISSUE THREAD

**Issue by andy200486** [contrix09/XF-Material-Library#230]
Hi all,

I'm having the following issue when building with the latest version of XF Material (1.5.7) : 

`Error MT2101: Can't resolve the reference 'System.Void System.Drawing.RectangleF::.ctor(System.Single,System.Single,System.Single,System.Single)', referenced from the method 'System.Void XF.Material.iOS.Renderers.Internals.MaterialEntryRenderer::AddRemoveReturnKeyToNumericInput(System.Boolean)' in 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. (MT2101) (RunChallenge.iOS)`

Xamarin iOS : 12.6.0.10
Xamarin Forms : 4.3.0.94

I'm running on VS2019 on High Sierra.

Thanks.

**Comment by OdetteP** [comment]
Can you please add the code or add it to the sample in github repro?
