### ISSUE TITLE
How to change text in Loading Dialog?

### ISSUE THREAD

**Issue by Auratos** [contrix09/XF-Material-Library#232]
I am using the package version 1.5.7. Platform - Xamarin Forms.
I can’t change the text a second time in the Loading Dialog. Is this a mistake in the module or should the text be changed in another way?

I do it like this:

LoadScreen("Step1", true);
LoadScreen("Step2", false);
LoadScreen("Step3", false); // At this point, the text no longer changes.
LoadScreen("Step4", false); // At this point, the text no longer changes.

async void LoadScreen(string str, bool flag)
        {
            try
            {
                if (flag)
                {
                    loadingDialog = await MaterialDialog.Instance.LoadingDialogAsync(message: str);
                }
                else
                    loadingDialog.MessageText = str;
            }
            catch (Exception ex)
            { }
        }

**Comment by OdetteP** [comment]
Did you try to do it like the sample in 'Change the dialog's text'  in 'Loading Dialog' in the Read.me https://github.com/Baseflow/XF-Material-Library#loading-dialog

**Comment by Auratos** [comment]
Do you mean this example? Yes
using(var dialog = await MaterialDialog.Instance.LoadingDialogAsync(message: "Something is running"))
{
    await Task.Delay(5000) // Represents a task that is running.
    dialog.Text = "Something else is running now!";
    await Task.Delay(5000) // Represents a task that is running.
}
If I change the text only 1 time, then everything is fine. But I need to change the text more than 1 time. If you do it like this, then it doesn’t work

var loadingDialog = await MaterialDialog.Instance.LoadingDialogAsync (message: "Step1");
loadingDialog.MessageText = "Step2"; //work
loadingDialog.MessageText = "Step3"; //doesn’t work
loadingDialog.MessageText = "Step4"; //doesn’t work

**Comment by OdetteP** [comment]
In my PR you can see that my text dialog changes 4 times.
