### ISSUE TITLE
MaterialTextInput Design adjustment. 

### ISSUE THREAD

**Issue by manonaga2188** [contrix09/XF-Material-Library#233]
## 🏗 Enhancement Proposal

Can you please increase gap between floating label and input text in MaterialTextInput. Also reduce gap between input text and underline.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by OdetteP** [comment]
Can you please explain why you need it.

**Comment by manonaga2188** [comment]
![Untitled-1](https://user-images.githubusercontent.com/35101045/69311979-b95e3800-0c53-11ea-9bfd-1edffe1e5a3d.png)

**Comment by CarLoOSX** [comment]
same problem here. would be fantastic to get this feature.

**Comment by OdetteP** [comment]
The adjustment is fixed
