### ISSUE TITLE
Method `XF.Material.Forms.UI.MaterialRadioButton..ctor()' is inaccessible

### ISSUE THREAD

**Issue by tp16190** [contrix09/XF-Material-Library#24]
I am using materialradiobutton (single) control in my application but due to its protection level (You are using internal access modifier), I am unable to call its constructor. I am getting this error 
Method `XF.Material.Forms.UI.MaterialRadioButton..ctor()' is inaccessible.

It is access modifier error. So If you make it public then it should work.

**Comment by contrix09** [comment]
Hi. Yes that is intentional, since MaterialRadioButton is only used in MaterialRadioButtonGroup. I don't see any importance to why a single radio button will be used. What is your intended use?

**Comment by tp16190** [comment]
As I am using Listview for sorting items. I am also binding MaterialRadioButton in my sorting listview as my item (Label + MaterialRadioButton). Because I want to select only one item at a time how I can use MaterialRadioButtonGroup in list item. So I am using MaterialRadioButton instead of MaterialRadioButtonGroup.

See below image.


![materialbuttonuse](https://user-images.githubusercontent.com/8983699/48410809-bfc6f380-e765-11e8-9b2e-964bad23aa05.png)

**Comment by contrix09** [comment]
Ok, I can consider this. Expect the new release about later this week, just after I cleanup some codes.

**Comment by contrix09** [comment]
Released new version.
