### ISSUE TITLE
Pick list - Title

### ISSUE THREAD

**Issue by gimenezfrg** [contrix09/XF-Material-Library#243]
541/5000
Hello, I tried to create a selection list using MaterialTextField with InputType = "Choice", but I can't muster the list title and the OK and CANCEL buttons, is it possible?

I wanted to use a list in a simple way, just as I do natively:
```
<Picker x: Name = "pcSexo" HorizontalOptions = "FillAndExpand" Title = "Type">
                     <Picker.Items>
                         <x: String> Jurídica</ x: String>
                         <x: String> Física</ x: String>
                     </Picker.Items>
                 </Picker>
```

**Comment by OdetteP** [comment]
It is not possible to change the title and 'Ok' and 'Cancel' buttons in the MaterialTextField InputType Choices.
