### ISSUE TITLE
If MaterialTextField InputType is password, the keyboard should be Default. Now it is Text.

### ISSUE THREAD

**Issue by manonaga2188** [contrix09/XF-Material-Library#247]
## 🐛 Bug Report

If I set InputType of MaterialTextField as Password, keyboard should be Default. This is the actual behavior.
Currently it is Keyboard.Text. It will open keyboard with CAPS ON and user has to turn off CAPS.

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by OdetteP** [comment]
I checked multiple old versions and it always has been Keyboard.Text for Password.

**Comment by manonaga2188** [comment]
@OdetteP I'm not saying it was default before. If it is Text, It force users every time to turn off CAPS. 

Difference between TEXT and Default 
Text - Opened keyboard with CAPS LOCK ON. Every time user has to turn off Caps then need to type password.
Default - Opened keyboard as default. Users no need to change CAPS LOCK(Unless they really want it).

I hope you understand my problem.

**Comment by OdetteP** [comment]
I tested InputType Password but in my case it did not open with CAPS LOCK ON. Everything is just as it should work. Check if you use IsAutoCapitalizationEnabled or IsTextAllCaps somewhere on the same MaterialTextField.
