### ISSUE TITLE
Multiple choice in MaterialRadioButtonGroup

### ISSUE THREAD

**Issue by mak100un** [contrix09/XF-Material-Library#252]
## 🐛 Bug Report

When you select a new item in the radio button the previous selected item not changed its status to unselected

### Expected behavior

When you select a new item the previous selected item will be deselected

### Reproduction steps

The problem occurred on Android

### Configuration

**Version:** 1.5.4
![image](https://user-images.githubusercontent.com/44783367/70269021-9c2c7c00-17b2-11ea-9bf6-238effae5770.png)

**Platform:** 
- [ ] :iphone: iOS
- [] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms 4.3+

**Comment by mak100un** [comment]
Usage
XAML:
<ui:MaterialRadioButtonGroup x:Name="QuestionTypeRadioButtonGroup"
                                                             VerticalSpacing="0"
                                                             SelectedColor="{StaticResource CardColor}"
                                                                HorizontalOptions="Start"
                                                                TextColor="{DynamicResource DarkTextColor}"                                            SelectedIndexChanged="QuestionTypeRadioButtonGroup_OnSelectedIndexChanged"/>

C#:
Constructor:
QuestionTypeRadioButtonGroup.Choices = new List<string>
            {
                TranslateFromCodeExtension.GetTranslation("InputQuestionType"),
                TranslateFromCodeExtension.GetTranslation("SelectOneQuestionType"),
                TranslateFromCodeExtension.GetTranslation("SelectAnyQuestionType")
            };

 private void QuestionTypeRadioButtonGroup_OnSelectedIndexChanged(object sender, SelectedIndexChangedEventArgs e)
        {
            switch (e.Index)
            {
                   Do something
             }
        }

**Comment by prakash-malodiya** [comment]
This issue also found in my project. @OdetteP  please update nuget package as soon as possible.

**Comment by mak100un** [comment]
> This issue also found in my project. @OdetteP please update nuget package as soon as possible.

Update what packages? The last versions of Xf Matarial was installed in my project

**Comment by ValonK** [comment]
I also have the same issue with the latest version

**Comment by OdetteP** [comment]
Try updated version 1.5.8

**Comment by gimenezfrg** [comment]
I upgraded to version 1.5.8 and still have the same problem. Xamarin Forms 4.4.991477.

Any solution?

**Comment by fdmomtaz** [comment]
The same issue is present on iOS.

**Comment by iglesiasfernando** [comment]
Yo can use a customRenderer on forms. an override indexChange method
` class FormRadio : MaterialRadioButtonGroup
    {
        Element container;
        public FormRadio()
        {
            
        }
        
        protected override void OnChildAdded(Element child)
        {
            base.OnChildAdded(child);
            container = child;
        }
        protected override void OnSelectedIndexChanged(int selectedIndex)
        {
            base.OnSelectedIndexChanged(selectedIndex);
            var index = 0;

            StackLayout element = container as StackLayout;
            foreach(MaterialRadioButton materialRadioButton in element.Children)
            {
                if(index != selectedIndex)
                {
                    materialRadioButton.IsSelected = false;
                }
                index++;
            }
        }

    }`

and you can use it from xaml like this:
`<customrenderers:FormRadio Choices="{Binding RadioList}"/>`
