### ISSUE TITLE
LoadingDialogAsync crashes on Rg.Plugins.Popup.Pages for android

### ISSUE THREAD

**Issue by kwabenaowusujnr** [contrix09/XF-Material-Library#253]
## 🐛 Bug Report
App crashes for  MaterialDialog.Instance.LoadingDialogAsync on Rg.Plugins.Popup.Pages.

**System.InvalidOperationException:** 'The page has not been pushed yet or has been removed already'

[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: The page has not been pushed yet or has been removed already
12-09 17:50:26.330 E/mono-rt (21054):   at Rg.Plugins.Popup.Services.PopupNavigationImpl.RemovePageAsync (Rg.Plugins.Popup.Pages.PopupPage page, System.Boolean animate) [0x00052] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:128 
12-09 17:50:26.330 E/mono-rt (21054):   at XF.Material.Forms.UI.Dialogs.BaseMaterialModalPage.DismissAsync () [0x00011] in /Users/martijn/Documents/OpenSource/XF-Material-Library/XF.Material/UI/Dialogs/BaseMaterialModalPage.cs:55 
12-09 17:50:26.330 E/mono-rt (21054):   at XF.Material.Forms.UI.Dialogs.BaseMaterialModalPage.ShowAsync () [0x0008f] in /Users/martijn/Documents/OpenSource/XF-Material-Library/XF.Material/UI/Dialogs/BaseMaterialModalPage.cs:144 
12-09 17:50:26.330 E/mono-rt (21054):   at XF.Material.Forms.UI.Dialogs.MaterialLoadingDialog.Loading (System.String message, XF.Material.Forms.UI.Dialogs.Configurations.MaterialLoadingDialogConfiguration configuration) [0x00032] in /Users/martijn/Documents/OpenSource/XF-Material-Library/XF.Material/UI/Dialogs/MaterialLoadingDialog.xaml.cs:32 

### Expected behavior
A loading dialog is supposed to show. Worked fine with previous version of XF.Material.

Usage:
var  loadingDialog = await MaterialDialog.Instance.LoadingDialogAsync(
               message: "Setting up page. Please Wait....",
               configuration: loadingDialogConfiguration
               );

### Configuration
XF.Material 1.5.7
Xamarin.Forms 4.2.0.910310
Rg.Plugins.Popup 1.2.0.223

**Platform:** 
- [* ] :monkey: Xamarin.Forms

**Comment by kwabenaowusujnr** [comment]
Please any progress on this, app is in production and users are experiencing caches.

**Comment by OdetteP** [comment]
Does the try catch from #224 works for you? Because I tried to replicate but I do not get this error.

**Comment by fakhravari** [comment]
how fontsize?
