### ISSUE TITLE
Resize text in a dialog

### ISSUE THREAD

**Issue by Auratos** [contrix09/XF-Material-Library#256]
## 💬 Questions and Help

Hello. Please tell me, is it possible to change the size of the text in the dialog in the code? I saw MaterialTypeScale.H1 ... MaterialTypeScale.Overline in the description. But I could not figure out how to apply this in code.

MaterialAlertDialogConfiguration alertDialogConfiguration = new MaterialAlertDialogConfiguration
        {
            BackgroundColor = Color.White,
            TitleTextColor = Color.FromHex("#16316F"),
            MessageTextColor = Color.FromHex("#16316F"),
            TintColor = Color.FromHex("#16316F"),
            CornerRadius = 8,
            ScrimColor = Color.FromHex("#16316F").MultiplyAlpha(0.32),
            ButtonAllCaps = true
        };

**Comment by OdetteP** [comment]
You can apply a type scale to a text using MaterialLabel. See Link
https://github.com/Baseflow/XF-Material-Library#applying-a-type-scale
