### ISSUE TITLE
MaterialTextField issue with HasError

### ISSUE THREAD

**Issue by alistairdyer** [contrix09/XF-Material-Library#257]
When the HasError is true the ErrorText is updating HelperText with the error message.  If you do not bind the HelperText (not using it) the error message still persists even when HasError is false.  The text color however is normal.  A workaround is to bind HelperText even if you don't want to use it.  

There is a similar issue when HasError has been set for the UnderLineColor.  On initial setting of HasError to true the underline changes to Red, however it stays red when HasError is false. On entering the MaterialTextField it is set back to the correct color as there isn't an error.

This is misleading to the user as it appears there is something wrong with their entry.

**Comment by OdetteP** [comment]
Can you please provide more detail and maybe a sample code and pictures?
