### ISSUE TITLE
Cast MaterialTextField as Entry

### ISSUE THREAD

**Issue by joshkautz** [contrix09/XF-Material-Library#258]
## 💬 Questions and Help

I have successfully followed the [instructions](https://mikalaidaronin.info/blog/posts/xamarin-forms-password-autofill/) to implement a  _Password AutoFill_ effect on Xamarin.Forms Entry elements - this is behaving properly on both Android and iOS platforms. However, I am unable to get the effect to work when I use it on the MaterialTextField element from the [XF.Material](https://github.com/Baseflow/XF-Material-Library) library.

I believe that the issue comes down to the native effect implementation for both iOS and Android, where I cast the xamarin form elements to native platform elements; in Android I need to use an EditText element, while in iOS I need to use a UITextField element. I haven't been able to cast the MaterialTextField to either of these elements.

Is this even possible using the XF.Material library element like this? Any suggestions would be greatly appreciated! Thank you to everyone in this community!

**Comment by OdetteP** [comment]
Did you tried this? https://github.com/Baseflow/XF-Material-Library#styling-input-dialogs
