### ISSUE TITLE
RadioButtonGroup isn't showing radio buttons 

### ISSUE THREAD

**Issue by karant0007** [contrix09/XF-Material-Library#259]
## 🐛 Bug Report

RadioButtonGroup isn't showing radio buttons with Xamarin.froms Android,
I have tried this with ios and it's working fine there.

![1577102290342](https://user-images.githubusercontent.com/13939526/71356937-c26f5b80-25a9-11ea-8bbc-9ab83bbcf49b.JPEG)

**Version:** 1.5.7

**Platform:** 

- [ ] :robot: Android
- [ ] :monkey: Xamarin.Forms

**Comment by jeroen-corteville** [comment]
I have the same issue, even normal radiobuttons aren't appearing

**Comment by OdetteP** [comment]
I have checked the Radio Buttons but in my case they are working fine in Android and iOS

**Comment by karant0007** [comment]
@OdetteP 
can you please check with latest xamarin.forms version 
i think this will be the case.

I'm asking this cause one other guy has faced same issue.

**Comment by OdetteP** [comment]
Try updated version 1.5.8
