### ISSUE TITLE
error in app release 

### ISSUE THREAD

**Issue by hassanjlilati** [contrix09/XF-Material-Library#270]
![‏لقطة الشاشة ٢٠٢٠-٠١-٢٠ في ٧ ٢٠ ٥٦ م](https://user-images.githubusercontent.com/29522038/72746544-0e1e2080-3bbb-11ea-9c06-638e16157ad7.png)
## 🐛 Bug Report

hello, thanks for your great plugin, it works like expected but when releasing IOS app the error that  in the attached image  is appearing   and no way to solve it when I set linker to  link framework SDK only 
no workaround for it even when  I skipped  the assembly  
### Expected behavior
app release normally 
### Configuration
visual studio  2017 for mac
xamarin forms the latest version 
**Version:** 1.5.8
 and the error in all plugin version, please help ASAP

**Platform:** 
- [1 ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by OdetteP** [comment]
Can you please provide me with more details and code.

**Comment by hassanjlilati** [comment]
Fixed issues  after update  visual  studio to 2019. Thanks
