### ISSUE TITLE
Multiple choice in MaterialRadioButtonGroup

### ISSUE THREAD

**Issue by gimenezfrg** [contrix09/XF-Material-Library#272]
Same problem reported in: https://github.com/Baseflow/XF-Material-Library/issues/252

![WhatsApp Image 2020-01-23 at 11 12 54](https://user-images.githubusercontent.com/13823246/72991901-96760e80-3dd1-11ea-845c-9f9eeeb14031.jpeg)

I upgraded to version 1.5.8 and still have the same problem. Xamarin Forms 4.4.991477.

Any solution?

**Comment by gimenezfrg** [comment]
???

**Comment by ValonK** [comment]
We are experiencing the same Issue

**Comment by manonaga2188** [comment]
Same fundamental issue...

**Comment by iglesiasfernando** [comment]
Yo can use a customRenderer on forms and override indexChange method
`class FormRadio : MaterialRadioButtonGroup
    {
        Element container;
        public FormRadio()
        {
            
        }
        
        protected override void OnChildAdded(Element child)
        {
            base.OnChildAdded(child);
            container = child;
        }
        protected override void OnSelectedIndexChanged(int selectedIndex)
        {
            base.OnSelectedIndexChanged(selectedIndex);
            var index = 0;

            StackLayout element = container as StackLayout;
            foreach(MaterialRadioButton materialRadioButton in element.Children)
            {
                if(index != selectedIndex)
                {
                    materialRadioButton.IsSelected = false;
                }
                index++;
            }
        }

    }`

and you can use it from xaml like this:
`<customrenderers:FormRadio Choices="{Binding RadioList}"/>`

**Comment by andrezakellen** [comment]
thanks @iglesiasfernando ! we are becoming this library in a collection of workarounds!

Thanks.
