### ISSUE TITLE
The type or namespace name 'Droid' does not exist in the namespace 'XF.Material'

### ISSUE THREAD

**Issue by Kriknu** [contrix09/XF-Material-Library#291]
## 🔙 Regression
Updated from 1.5.8 to 1.6.0 recently and cannot call the method Init in MainActivity.cs. The error Im getting is "The type or namespace 'Droid' does not exist in the namespace 'XF.Material' (are you missing an assembly reference?)"

I am admittingly new to Xamarin and C#, and this may very well be an error caused by my lack of knowledge.

**Version:** 1.6.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by ske66** [comment]
Seems to be a pretty breaking change. +1. For the meantime, regress to version 1.5.8 in Nuget

**Comment by mtsrdr** [comment]
You have to migrate your android project to AndroidX. Set the Target Framework to Android 10 in your project settings and the targetSdkVersion to 29 in your AndroidManifest file.

**Comment by martijn00** [comment]
Update to AndroidX and target Android 10.

**Comment by Alextorres950325** [comment]
I migrate my project to Android X an change and Set the Target Framework to Android 10 in my project settings and the targetSdkVersion to 29 in my AndroidManifest file. But the  type or namespace name 'Droid' does not exist in the namespace 'XF.Material' message persist
