### ISSUE TITLE
Null Reference Exception when initializing XF-Material on Android

### ISSUE THREAD

**Issue by ske66** [contrix09/XF-Material-Library#292]
## 🔙 Regression

Version 1.6 seems to contain a breaking change regarding the initialization of the package in the Android MainActivity class. 

### Old (and correct) behavior

Project compiles and runs successfully

### Current behavior

program fails to start with a Null Reference Exception

### Reproduction steps

- Upgrade to version 1.6

- Initialize XF-Material in MainActivity.cs using;
    `XF.Material.Droid.Material.Init(this, savedInstanceState);`

- Compile and start the application

### Configuration

**Version:** 1.6

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by mtsrdr** [comment]
You have to migrate your android project to AndroidX. Set the Target Framework to Android 10 in your project settings and the targetSdkVersion to 29 in your AndroidManifest file.

**Comment by martijn00** [comment]
@mtsrdr +1

**Comment by stephenhauck** [comment]
I'm running version 1.7.8 and I'm getting this ...
![image](https://user-images.githubusercontent.com/12648793/135694923-b03fb085-80a3-4dd6-9708-6c4a8660b31f.png)
![image](https://user-images.githubusercontent.com/12648793/135694937-5432a00b-4a89-47f3-b0e0-0a2f731d77af.png)
