### ISSUE TITLE
No XF.Material.Droid in version 1.6.0

### ISSUE THREAD

**Issue by Redp87** [contrix09/XF-Material-Library#298]
## 🐛 Bug Report

No XF.Material.Droid in version 1.6.0
When I update to version 1.6.0, it says No XF.Material.Droid!

**Version:** 1.6.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Slm0nB** [comment]
Hello
I am experiencing the same issue, looking forward to being able to use the new features.

**Comment by fgbustoa** [comment]
Already answered in #291
