### ISSUE TITLE
Android 7.1

### ISSUE THREAD

**Issue by dzombeast** [contrix09/XF-Material-Library#3]
Hi!

I was wondering if it would be possible the get this awesome library to run on Xamarin.Forms dev for android 7.1. I've tried getting the lowest version over Nuget, but I've got compatibility issues with Xamarin.Android.Support.* version, since 25.4.0.2 is the highest I can go with. Perhaps I'm missing something?

Many thanks!

Cheers,

**Comment by dzombeast** [comment]
Hi!

Thank you very much!

Because I'm working with an RFID industrial device, which at the moment supports Andorid 7.1. only and, unfortunately, I don't believe they gonna be updating any time soon.

Cheers,

**Comment by contrix09** [comment]
Ok, I see. I'll update you when I applied this request.

**Comment by contrix09** [comment]
Version 1.0.6 has been release. You can now install this package while using Xamarin.Android.Support.* versions 25.4.0.2 and above.

**Comment by dzombeast** [comment]
Hi!

Thank you ^^

Cheers,

**Comment by dzombeast** [comment]
Hi!

Sorry for bringing up Android 7.1 again :) I get the following error when I try to build the project:

`Xamarin.Android.Common.targets(1830,2): error XA2002: Can not resolve reference: `Lottie.Android`, referenced by `XF.Material.Droid`. Please add a NuGet package or assembly reference for `Lottie.Android`, or remove the reference to `XF.Material.Droid`. `

I've referenced Lottie 2.5.4 in Forms project. The lowest I can go in Android project is 2.5.1. Could this be the Issue?

Many thanks!

Cheers,

**Comment by contrix09** [comment]
Hi, just tested the package by lowering it `Lottie.Forms` version to `2.5.1`, there are breaking changes for projects that target greater than Android 7.1. In other words, I can't lower the minimum version.

**Comment by dzombeast** [comment]
Hi! That's a a shame, but many thanks!
