### ISSUE TITLE
MaterialTextField error label is not getting hide

### ISSUE THREAD

**Issue by pedro-gilmora** [contrix09/XF-Material-Library#300]
## 🐛 Bug Report

**MaterialTextField** error label is not hidden when change `ErrorText` to `String.Empty` and `HasError` to `false`

### Expected behavior

Hide the Error label when HasError = false

### Reproduction steps

```
private void ValidateText(object sender, TextChangedEventArgs e)
{
    var mtf = (MaterialTextField)sender;
    bool invalid = !mtf.Text.Trim().Any();
    if (mtf.HasError != invalid)
    {
        mtf.ErrorText = invalid ? "Required field" : "";
        mtf.HasError = invalid;
    }
}
```
**Version:** 1.5.8

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by lunjio** [comment]
Try update you package, it was a problem below 1.6 version

**Comment by Kylar182** [comment]
> Try update you package, it was a problem below 1.6 version

I'm having this issue with the current version, was there a work around?
