### ISSUE TITLE
Version 1.6.1 MaterialCard.Elevation problem

### ISSUE THREAD

**Issue by nftang** [contrix09/XF-Material-Library#310]
Just updated to 1.6.1, the following  exhibited errors while pervious versions are OK.

                            <material:MaterialCard.Elevation>
                                <OnPlatform x:TypeArguments="x:Int32">
                                    <OnPlatform.iOS>3</OnPlatform.iOS>
                                    <OnPlatform.Android>5</OnPlatform.Android>
                                </OnPlatform>
                            </material:MaterialCard.Elevation>

On the other hand, when using Xamarin Forms 4.5 onwards, need to declare the following, for iOS, to avoid double rendering of the original shadow of Forms (i.e., an all round dark shadow). Forms 4.4 works fine.

                            <material:MaterialCard.HasShadow>
                                <OnPlatform x:TypeArguments="x:Boolean">
                                    <On Platform="Android" Value="True" />
                                    <On Platform="iOS" Value="False" />
                                </OnPlatform>
                            </material:MaterialCard.HasShadow>

Francis

**Comment by mtsrdr** [comment]
Try changing the type to double in Elevation:

OnPlatform x:TypeArguments="x:Double"

About the shadows was fixed in the latest version.

**Comment by nftang** [comment]
Big thanks!

Worked like a charm.
