### ISSUE TITLE
MaterialTextField PlaceHolder

### ISSUE THREAD

**Issue by fgbustoa** [contrix09/XF-Material-Library#312]
## 🐛 Bug Report

I have a textfield with a bounded Text property.

I apply this style

            <Style TargetType="material:MaterialTextField">
                <Setter Property="AlwaysShowUnderline" Value="False" />
                <Setter Property="BackgroundColor" Value="LightGray" />
                <Setter Property="FloatingPlaceholderEnabled" Value="False" />
                <Setter Property="HorizontalOptions" Value="FillAndExpand" />
                <Setter Property="PlaceholderColor" Value="Transparent" />
                <Setter Property="TextColor" Value="Black" />
                <Setter Property="TextFontSize" Value="18" />
                <Setter Property="VerticalOptions" Value="FillAndExpand" />
            </Style>

and this my field XAML

<material:MaterialTextField ReturnType="Next" Text="{Binding SCLIPAddress, Mode=TwoWay}" />

MaterialField show my Text. When i click inside field, placeholder appears over text.

![Annotazione 2020-03-18 110314](https://user-images.githubusercontent.com/55985383/76948967-233bd500-6908-11ea-8330-444f9e2d0427.png)

ANOTHER QUESTION/REQUEST:
Please set placeholder as NOT MANDATORY, or at least let us set placeholder = "". THANKS

### Expected behavior

Obviously placeholder MUST NOT APPEAR

### Configuration

**Version:** 1.6.1

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by SnowPowerCore** [comment]
+1 having this problem with MaterialTextField using the latest version of this library 1.6.1
