### ISSUE TITLE
Android Nuget no longer has  XF.Material.Droid.Material.Init(() method

### ISSUE THREAD

**Issue by rogerwcpt** [contrix09/XF-Material-Library#313]
## 🔙 Regression

Can no longer call  XF.Material.Droid.Material.Init(this, savedInstanceState) in the Android AppActivity class. Method does not exist in the Android Package. 

### Old (and correct) behavior

XF.Material.Droid.Material.Init(this, savedInstanceState)

### Current behavior

**XF.Material.Droid.Material.Init**(this, savedInstanceState) does not exist.

### Reproduction steps

Install Nuget 1.6.1

### Configuration

**Version:** 1.6.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Update to Android 10. See the other issues
