### ISSUE TITLE
The back button still enable when LoadingDialog is showing

### ISSUE THREAD

**Issue by vincywindy** [contrix09/XF-Material-Library#32]
**Describe the bug**
When the LoadingDialog is showing the back button press will go to last page.

**To Reproduce**
Here‘s two page ：
```
public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
        }

        private async void Button_Clicked(object sender, EventArgs e)
        {
            View1 view1 = new View1();
           await Navigation.PushModalAsync(view1);
        }
    }
```

```
public partial class View1 : ContentPage
    {
        public View1()
        {
            InitializeComponent();
        }

        private async void Button_Clicked(object sender, EventArgs e)
        {
            var dialog = await MaterialDialog.Instance.LoadingDialogAsync(message: "获取数据中……");
            await Task.Delay(5000);
            dialog.Dispose();
        }
    }
```
When the loadingdialog is showing,I press back button on android,it back to MainPage, but the loadingdialog still showing,after 5s loadingdialog hide.

**Comment by AnthonyLatty** [comment]
How was this solved??

**Comment by contrix09** [comment]
Hi, please update to the latest version. And instead of calling`Dispose` to remove the dialog, you can now call `DismissAsync`.

**Comment by AnthonyLatty** [comment]
Thanks...Question is there a way to change the activity indicator color within the loading dialog??

**Comment by contrix09** [comment]
Yes, look for the overload method that takes the parameter of the type `MaterialLoadingDialogConfiguration`.

```c#
var loading = await MaterialDialog.Instance.LoadingDialogAsync("Please wait...", new XF.Material.Forms.UI.Dialogs.Configurations.MaterialLoadingDialogConfiguration
{
     TintColor = Color.Red
});
```

**Comment by contrix09** [comment]
For now the loading dialog cannot by dismissed by pressing the back button on Android. If you used it in a `using` block, it will automatically be dismissed once the task inside the has completed, no need to call the `DismissAsync`. I'm still looking for a way to create an implementation where the user can cancel the dialog along with the task that is running. May be next year though.

**Comment by AnthonyLatty** [comment]
Okay no problem.

**Comment by vincywindy** [comment]
I use new version 1.3.0.3,but the problem is same, I use this code:
```
 [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class View1 : ContentPage
    {
        public View1()
        {
            InitializeComponent();
        }

        private async void Button_Clicked(object sender, EventArgs e)
        {
            using (await MaterialDialog.Instance.LoadingDialogAsync(message: "Something is running"))
            {
                await Task.Delay(5000); // Represents a task that is running.
            }


        }
    }
```

**Comment by contrix09** [comment]
Hi, did you override the `OnBackPressed` on Android like this:

```c#
public override void OnBackPressed()
{
    XF.Material.Droid.Material.HandleBackButton(base.OnBackPressed);
}
```

**Comment by vincywindy** [comment]
No,so I need to override it?
