### ISSUE TITLE
Nuget for 1.6.3. seems to be broken

### ISSUE THREAD

**Issue by DeeRice** [contrix09/XF-Material-Library#322]
## 🐛 Bug Report Nuget for 1.6.3 seems to be broken

When download loading the nuget package for XF.Material, The nuget lacks the necessary platform specific dll;s
### Expected behavior
Nuget package gets downloaded containing necesary platform specifc dlls. Platform specific dlls gets installed to the correct projects
### Reproduction steps
download and install the nuget package for 1.6.3... trying to follow the tutorial on the readme (add code for Forms, then Android/iOS)... Try to compile and notice XF.Material.Droid/XF.Material.iOS is missing from library...Manually check the package to notice that the dlls are not there.
### Configuration

**Version:** 1.x

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [x] :apple: MacOS
- [x] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by parredondov** [comment]
Same issua with Droid

**Comment by SagarPanwala** [comment]
I've same issue, everything is broken now. After upgrading I can't compile the app.

**Comment by SagarPanwala** [comment]
@martijn00  This will be pushed in which Nuget Version ?

**Comment by martijn00** [comment]
It is not a bug. You target the wrong Android version

**Comment by SagarPanwala** [comment]
ohhh that's good to hear.
But I'm not able to find Xf.Material.Droid.

So you mean to say we don't have to call Init method anymore now for platform specific project?

**Comment by sandeshdaddi** [comment]
> ohhh that's good to hear.
> But I'm not able to find Xf.Material.Droid.
> 
> So you mean to say we don't have to call Init method anymore now for platform specific project?

Nope, you have to change the Target Android Framework as Andoird10  in you Android project.
