### ISSUE TITLE
Change Image type from string to ImageSource

### ISSUE THREAD

**Issue by leftas** [contrix09/XF-Material-Library#339]
## 🏗 Enhancement Proposal

I would suggest that Image property in MaterialIconButton(_or in any other control where Image is a string property_) should be changed to ImageSource. 

### Pitch

Developers wouldn't have to waste a lot of space including a lot of images in their app they want to use for buttons. They just could use font/stream/uri. 

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [X] :robot: Android
- [X] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [X] :apple: MacOS
- [X] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you make a PR for this?

**Comment by leftas** [comment]
> Can you make a PR for this?

Yeah, sure. Just I reckon that I will postpone it till weekend.

**Comment by leftas** [comment]
Closed with this https://github.com/Baseflow/XF-Material-Library/pull/342 pull.
