### ISSUE TITLE
Simple Dialog

### ISSUE THREAD

**Issue by AnthonyLatty** [contrix09/XF-Material-Library#34]
This is more of a question than a issue, how do i get the click events on each of the string in 

> MaterialDialog.Instance.SelectActionAsync()

**Comment by contrix09** [comment]
Hi. Unfortunately you can't. Once a choice is clicked, the dialog dismisses and returns the string that was selected.

**Comment by AnthonyLatty** [comment]
Hi. What i am trying to achieve is the click event of one dialog triggers a next dialog. So i taught there was a click event that was associated with the Dialog control

**Comment by contrix09** [comment]
You can check the returned string value of the dialog. It returns `string.Empty` if the dialog was dismissed other than when a choice was clicked. If the string is not empty, then show the other dialog.

**Comment by AnthonyLatty** [comment]
This is what i am attempting to do : 
`var actions = new string[] { "Test1", "Test2" };

  var result = MaterialDialog.Instance.SelectActionAsync("Select an option", actions);
if(actions[0] == "Test1"
{
   //Do something
}
else
{
    //Do something else
}
`

**Comment by contrix09** [comment]
Hi, my mistake. `SelectActionAsync` returns only the index of the selected choice. If the dialog was dismissed, it returns `-1`. You need to detect the negative index to avoid an exception.
```c#
var actions = new string[] { "Test1", "Test2" };
var result = MaterialDialog.Instance.SelectActionAsync("Select an option", actions);

if(result >= 0)
{
    switch(actions[result])
    {
        case "Test1": 
              MethodForSomething();
              break;
        case "Test2": 
              MethodForSomethingElse();
              break;
    }
}
```

You can also use this.
```c#
var actions = new string[] { "Test1", "Test2" };
var result = MaterialDialog.Instance.SelectActionAsync("Select an option", actions);

switch(result)
{
    case -1:
          MethodForNoAction();
          break;
    case 0: 
          MethodForSomething();
          break;
    case 1: 
          MethodForSomethingElse();
          break;
}
```

**Comment by AnthonyLatty** [comment]
Would i have to Dispose() of the previous dialog to see the new one?? I added a method with the same code: 
`var actions = new string[] { "Test3", "Test4" };
var result = MaterialDialog.Instance.SelectActionAsync("Select an option", actions);`

and i am not seeing this dialog when i tapped on "Test1"

**Comment by contrix09** [comment]
No need to dispose. Add the `await` keyword before calling the method.
```c#
var result = await MaterialDialog.Instance.SelectActionAsync("Select an option", actions);
```

**Comment by AnthonyLatty** [comment]
Ok thanks, i got it to work for my use case.

**Comment by AnthonyLatty** [comment]
This is the code i have but it doesnt display a next dialog

```
var actions = new string[] { "Residents 1", "Residents 2" };

var result = await MaterialDialog.Instance.SelectActionAsync("Select an option", actions);

switch (result)
{
   case -1:
       break;
   case 0:
       var resident1 = new string[] { "Home", "Away" };
       var result1 = await MaterialDialog.Instance.SelectActionAsync("Residents 1", resident1);
       break;
   case 1:
       var resident2 = new string[] { "Local", "Away" };
       var result2 = await MaterialDialog.Instance.SelectActionAsync("Residents 2", resident2);
       break;
}
```
No new dialog appears

**Comment by contrix09** [comment]
Hi. After some investigation, I saw the problem. The result is being returned but before showing the next dialog, it was dismissed immediately since the disappearing animation of the first dialog was still not finished.

**Comment by AnthonyLatty** [comment]
Ok thats good because i taught i was misusing the library. Is is possible to allow the animation of the first dialog to disappear on click?

**Comment by AnthonyLatty** [comment]
Will test when its released

**Comment by AnthonyLatty** [comment]
Tested it, works as expected.
