### ISSUE TITLE
Image tint color in MaterialMenuDialog

### ISSUE THREAD

**Issue by leftas** [contrix09/XF-Material-Library#344]
## 🏗 Enhancement Proposal

The image color should not be dependant of the Label's TextColor. Thus, I suggest removing image's TintColor binding from text color completely or implement a new property which would tint the image to developer's liking.

### Platforms affected (mark all that apply)
- [X] :iphone: iOS
- [X] :robot: Android
- [X] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [X] :apple: MacOS
- [X] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you make a PR to fix this?

**Comment by leftas** [comment]
Yes.
However, @martijn00, I am not sure how you imagine it ? Whether remove it completely or add a new property for tinting the image ?
