### ISSUE TITLE
Old binding left - hogging the performance

### ISSUE THREAD

**Issue by leftas** [contrix09/XF-Material-Library#345]
## 🐛 Bug Report

`Binding: 'RowHeight' property not found on 'Xamarin.Forms.StackLayout', target property: 'XF.Material.Forms.UI.Internals.MenuDialogLabel.HeightRequest'`
I think the message pretty much sums up the bug.

It seems that the bug was created by this commit: https://github.com/Baseflow/XF-Material-Library/commit/ad31005852e122b0a830a2520655956739d02b0f 
Since it was changed from ListView to StackLayout. And Stacklayout does not have RowHeight as a property.

### Expected behavior

That material menu would load faster?

### Reproduction steps

Create MenuButton and add some choices. If you open you would encounter this Binding error.

### Configuration

**Version:** 1.6.5

**Platform:** 
- [X] :iphone: iOS
- [X] :robot: Android
- [X] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [X] :apple: MacOS
- [X] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you make a PR to fix this?

**Comment by leftas** [comment]
Yes.
