### ISSUE TITLE
Access Color and Font Resource in xaml

### ISSUE THREAD

**Issue by babduljameel** [contrix09/XF-Material-Library#347]
How can I access color or font resource in xaml with xf library..

I event tried to set the background color of button using 
`Color primaryColor = XF.Material.Forms.Material.Color.Primary;`
but it didnt work...please help

**Comment by ske66** [comment]
Are you doing c# markup or xaml? if it's xaml you would add the color to your static resource list and then do;

`<ui:MaterialButton BackgroundColor="{StaticResource Material.Color.Background}" />`
