### ISSUE TITLE
AppDelegate does not recognize XF.Material.iOS.Material.Init()

### ISSUE THREAD

**Issue by rajinpangkalpundai** [contrix09/XF-Material-Library#349]
## 💬 Questions and Help
**Description**
My AppDelegate doesn't recognize the XF namespace when i want to call XF.Material.iOS.Material.Init() method, while both Xamarin.Forms and Xamarin.Android are working fine.

Here's the detail:
Error "The name 'XF' does not exist in the current context".

**I'm using**
Xamarin.Forms v4.7.0.1260
XF.Material v1.6.5

**Comment by Kuurse** [comment]
Same issue here, except that it is in my Android project that the class `Droid` is missing.

**Comment by martijn00** [comment]
Add it to the platform itself and target the right version

**Comment by Kuurse** [comment]
I'm sorry, I don't know what you mean. The package is definitely added to my Xamarin.Android project (I just upgraded it to 1.66) but it still can't find the `Droid` namespace. Could you please be more specific as to what I am supposed to do to get it working?

**Comment by rajinpangkalpundai** [comment]
Thank you @martijn00, it works now!
