### ISSUE TITLE
Updating the CanExecute command property for a disposed MaterialButton causes a crash

### ISSUE THREAD

**Issue by michaelkollmann** [contrix09/XF-Material-Library#35]
**Describe the bug**
When updating the CanExecute property for an already disposed MaterialButton a crash occours.
This issue does not exist when using the regular Xamarin.Forms Button.

**To Reproduce**
1. My application opens a modal dialog page
2. In this dialog I click a "Save" button which closes the dialog
3. To prevent clicking the button twice the command sets the CanExecute property to false while the command is being executed
3. Now the dialog has been closed and is starting to be disposed. The command completes and the CanExecute property changes back from false to true.
4. Now the application crashes with the following error:

`System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Android.Support.V7.Widget.AppCompatButton'.`

I'm using the latest XF.Material library, version 1.3.0.2. All my Xamarin.Android.* libraries are version 28.0.0

**Expected behavior**
The application does not crash.

**Screenshots**

**Environment:**
 - Device: Xiaomi Red mi 2
 - OS: Android 8.1

**Comment by contrix09** [comment]
Will look into this.

**Comment by contrix09** [comment]
I can't seem to replicate this. What do you to show the modal page?

**Comment by yankarinRG** [comment]
Still persists as of 1.6.4
