### ISSUE TITLE
iOS: no icon visible at all (assets seems to be missing?)

### ISSUE THREAD

**Issue by softlion** [contrix09/XF-Material-Library#359]
## 🐛 Bug Report
On iOS, material fields don't display any asset. Especially the "delete content" icon on material entries is not displayed. But it is general: there is no icon at all displayed by the library.
The same code does work fine on Android, and all icons are displayed correctly.

### Expected behavior
On iOS, MaterialTextField should display the "cross" icon to delete its content

### Reproduction steps
Run the existing sample project on an iPhone 6 iOS 12.4 simulator.
Open the text fields test page.

### Configuration

**Version:** 1.6.6 and also locally built version 1.6.7-pre2 from my own clone of this repo

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by softlion** [comment]
It seems to be a bug in Sdk Extra.

https://github.com/novotnyllc/MSBuildSdkExtras/issues/170
https://github.com/novotnyllc/MSBuildSdkExtras/issues/169

**Comment by softlion** [comment]
Also, xf_clear is not available on iOS. There is only an Android resource. So that explains why the clear button won't appear on iOS.

**Comment by lunjio** [comment]
You can solve this problem by manually adding images files in your project. I tried to solve the problem many times, checked everything, project is correct, may be there are problem in dashes in file names. However manually adding all images to your IOS project solves problem. i also compared the library with others existing, where embeded images display correct, didn't noticed any difference

**Comment by softlion** [comment]
I've PR to add the missing "xf_clear".
@lunjio The setup doc should be temporarily updated to reflect this.

**Comment by softlion** [comment]
dup of #327
PR done for the missing icon.
