### ISSUE TITLE
MaterialMenuButton Menu Sizing

### ISSUE THREAD

**Issue by eceowl** [contrix09/XF-Material-Library#36]
**Describe the bug**
On Android, the menu of the MaterialMenuButton appears to calculate it's width based on the length of the last choice in the choice list.  If choices before the last choice are longer, it truncates them.

**To Reproduce**
Create a MaterialMenuButton with multiple choices where the length of the last string is shorter than the length of the other choices.

**Expected behavior**
All choices should fit in the menu regardless of the order in which they are placed. 

**Screenshots**
![screenshot_20181219-142135](https://user-images.githubusercontent.com/4378173/50243008-f2ce5980-0399-11e9-9777-0912e5971df9.jpg)
![screenshot_20181219-142301](https://user-images.githubusercontent.com/4378173/50243016-f7930d80-0399-11e9-8c5c-22ddc8e37edc.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9+

**Comment by eceowl** [comment]
Update: On iOS it cuts off too but even if I put the longest at the bottom

**Comment by contrix09** [comment]
Will look into this.

**Comment by contrix09** [comment]
Hi, this issue has been fixed. Will release the new version later. Keep in mind that the menu has a maximum width of `280`, and a minimum width of `112`.
