### ISSUE TITLE
XF.Material.Droid.Renderers.MaterialCircularLoadingViewRenderer Error

### ISSUE THREAD

**Issue by mmk90** [contrix09/XF-Material-Library#39]
Hi
I am a new Xamarin developer and I want to use this wonderful plugin in my project and i install every essential plugins from nuget for this plugin and then install this plugin but when I run my android application i get this error :
**[System.TypeLoadException: Could not load type XF.Material.Droid.Renderers.MaterialCircularLoadingViewRenderer while decoding custom attribute: (null)]**
I get this error exatcly in this line:
**[global::Xamarin.Forms.Forms.Init(this, savedInstanceState);]**
and I have no idea how should I solve this problem.
by the way i use android 5 and target framework is set on android 8 and the minimum api is 21
and this is my onCreate method:

        protected override void OnCreate(Bundle savedInstanceState)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(savedInstanceState);

            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);

            XF.Material.Droid.Material.Init(this, savedInstanceState);
            LoadApplication(new App());
        }
Thank You

**Comment by contrix09** [comment]
Hi, please add also the `XF.Material.Forms.Material.Init(this)` method in your Forms project `App.cs`, right after `this.InitializeComponent()`.

**Comment by karner** [comment]
Hi, sorry for commenting on the closed issue, but maybe this can help. This seems to be caused by a version conflict with lottie. These are my nugets - with these versions it does work:

Xamarin.Forms project:
```
    <PackageReference Include="Acr.UserDialogs" Version="7.0.1" />
    <PackageReference Include="Com.Airbnb.Xamarin.Forms.Lottie" Version="2.5.4" />
    <PackageReference Include="Flurl.Http" Version="2.4.0" />
    <PackageReference Include="Microcharts" Version="0.7.1" />
    <PackageReference Include="Microcharts.Forms" Version="0.7.1" />
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="1.13.0" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="1.13.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="2.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.1" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="2.2.0" />
    <PackageReference Include="modernhttpclient" Version="2.4.2" />
    <PackageReference Include="Xam.Plugin.Media" Version="4.0.1.5" />
    <PackageReference Include="Xamarin.Essentials" Version="1.0.1" />
    <PackageReference Include="Xamarin.Forms" Version="3.4.0.1009999" />
    <PackageReference Include="Prism.DryIoc.Forms" Version="7.1.0.431" />
    <PackageReference Include="Xamarin.Forms.GoogleMaps" Version="3.0.4" />
    <PackageReference Include="XF.Material" Version="1.2.4" />
```

Xamarin.Android project:
```

    <PackageReference Include="Acr.UserDialogs">
      <Version>7.0.1</Version>
    </PackageReference>
    <PackageReference Include="Com.Airbnb.Xamarin.Forms.Lottie">
      <Version>2.5.4</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite">
      <Version>2.2.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Localization">
      <Version>2.2.0</Version>
    </PackageReference>
    <PackageReference Include="modernhttpclient">
      <Version>2.4.2</Version>
    </PackageReference>
    <PackageReference Include="System.Buffers">
      <Version>4.5.0</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.Media">
      <Version>4.0.1.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Essentials">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms" Version="3.4.0.1009999" />
    <PackageReference Include="Xamarin.Android.Support.Design" Version="27.0.2.1" />
    <PackageReference Include="Xamarin.Android.Support.v7.AppCompat" Version="27.0.2.1" />
    <PackageReference Include="Xamarin.Android.Support.v4" Version="27.0.2.1" />
    <PackageReference Include="Xamarin.Android.Support.v7.CardView" Version="27.0.2.1" />
    <PackageReference Include="Xamarin.Android.Support.v7.MediaRouter" Version="27.0.2.1" />
    <PackageReference Include="Prism.DryIoc.Forms" Version="7.1.0.431" />
    <PackageReference Include="Xamarin.Forms.GoogleMaps">
      <Version>3.0.4</Version>
    </PackageReference>
    <PackageReference Include="XF.Material">
      <Version>1.2.4</Version>
    </PackageReference>
```

I had lottie at v 2.7.0, XF.Material at 1.3.1 and got the problem. Downgrading Lottie to 2.5.4 and XF.Material to 1.2.4 solved it for me.

**Comment by didacvm** [comment]
> 
> 
> Hi, sorry for commenting on the closed issue, but maybe this can help. This seems to be caused by a version conflict with lottie. These are my nugets - with these versions it does work:
> 
> Xamarin.Forms project:
> 
> ```
>     <PackageReference Include="Acr.UserDialogs" Version="7.0.1" />
>     <PackageReference Include="Com.Airbnb.Xamarin.Forms.Lottie" Version="2.5.4" />
>     <PackageReference Include="Flurl.Http" Version="2.4.0" />
>     <PackageReference Include="Microcharts" Version="0.7.1" />
>     <PackageReference Include="Microcharts.Forms" Version="0.7.1" />
>     <PackageReference Include="Microsoft.AppCenter.Analytics" Version="1.13.0" />
>     <PackageReference Include="Microsoft.AppCenter.Crashes" Version="1.13.0" />
>     <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="2.2.1" />
>     <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.1" />
>     <PackageReference Include="Microsoft.Extensions.Localization" Version="2.2.0" />
>     <PackageReference Include="modernhttpclient" Version="2.4.2" />
>     <PackageReference Include="Xam.Plugin.Media" Version="4.0.1.5" />
>     <PackageReference Include="Xamarin.Essentials" Version="1.0.1" />
>     <PackageReference Include="Xamarin.Forms" Version="3.4.0.1009999" />
>     <PackageReference Include="Prism.DryIoc.Forms" Version="7.1.0.431" />
>     <PackageReference Include="Xamarin.Forms.GoogleMaps" Version="3.0.4" />
>     <PackageReference Include="XF.Material" Version="1.2.4" />
> ```
> 
> Xamarin.Android project:
> 
> ```
> 
>     <PackageReference Include="Acr.UserDialogs">
>       <Version>7.0.1</Version>
>     </PackageReference>
>     <PackageReference Include="Com.Airbnb.Xamarin.Forms.Lottie">
>       <Version>2.5.4</Version>
>     </PackageReference>
>     <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite">
>       <Version>2.2.1</Version>
>     </PackageReference>
>     <PackageReference Include="Microsoft.Extensions.Localization">
>       <Version>2.2.0</Version>
>     </PackageReference>
>     <PackageReference Include="modernhttpclient">
>       <Version>2.4.2</Version>
>     </PackageReference>
>     <PackageReference Include="System.Buffers">
>       <Version>4.5.0</Version>
>     </PackageReference>
>     <PackageReference Include="Xam.Plugin.Media">
>       <Version>4.0.1.5</Version>
>     </PackageReference>
>     <PackageReference Include="Xamarin.Essentials">
>       <Version>1.0.1</Version>
>     </PackageReference>
>     <PackageReference Include="Xamarin.Forms" Version="3.4.0.1009999" />
>     <PackageReference Include="Xamarin.Android.Support.Design" Version="27.0.2.1" />
>     <PackageReference Include="Xamarin.Android.Support.v7.AppCompat" Version="27.0.2.1" />
>     <PackageReference Include="Xamarin.Android.Support.v4" Version="27.0.2.1" />
>     <PackageReference Include="Xamarin.Android.Support.v7.CardView" Version="27.0.2.1" />
>     <PackageReference Include="Xamarin.Android.Support.v7.MediaRouter" Version="27.0.2.1" />
>     <PackageReference Include="Prism.DryIoc.Forms" Version="7.1.0.431" />
>     <PackageReference Include="Xamarin.Forms.GoogleMaps">
>       <Version>3.0.4</Version>
>     </PackageReference>
>     <PackageReference Include="XF.Material">
>       <Version>1.2.4</Version>
>     </PackageReference>
> ```
> 
> I had lottie at v 2.7.0, XF.Material at 1.3.1 and got the problem. Downgrading Lottie to 2.5.4 and XF.Material to 1.2.4 solved it for me.

Just downgrading Lottie to 2.5.4 solved it for me. Thank you anyways @karner

**Comment by martijn00** [comment]
All your nugets are years old. Upgrade to the latest of everything and it works.
