### ISSUE TITLE
Throws exception when trying to open any dialog If the "MaterialConfiguration" provided in "Material.Init"

### ISSUE THREAD

**Issue by TameemHabash** [contrix09/XF-Material-Library#390]
When I tried to change the default theme by providing an object of type "MaterialConfiguration" in the "XF.Material.Forms.Material.Init()" method, after that, it throws an exception when trying to open any dialog, even the dialog of the MaterialTextField (with InputType="Choice").
here is the full exception:
`{Xamarin.Forms.Xaml.XamlParseException: Position 22:32. StaticResource not found for key Material.Dialog.Width  at Xamarin.Forms.Xaml.StaticResourceExtension.ProvideValue (System.IServiceProvider serviceProvider) [0x0008f] in D:\a\1\s\Xamarin.Forms.Xaml\MarkupExtensions\StaticResourceExtension.cs:27   at XF.Material.Forms.UI.Dialogs.MaterialSimpleDialog.InitializeComponent () [0x00055] in C:\Users\mhvdi\Documents\OpenSource\XF-Material-Library\XF.Material\obj\Release\monoandroid10.0\UI\Dialogs\MaterialSimpleDialog.xaml.g.cs:38   at XF.Material.Forms.UI.Dialogs.MaterialSimpleDialog..ctor (XF.Material.Forms.UI.Dialogs.Configurations.MaterialSimpleDialogConfiguration configuration) [0x00006] in C:\Users\mhvdi\Documents\OpenSource\XF-Material-Library\XF.Material\UI\Dialogs\MaterialSimpleDialog.xaml.cs:21   at XF.Material.Forms.UI.Dialogs.MaterialSimpleDialog.ShowAsync (System.String title, System.Collections.Generic.IEnumerable`
`1[T] actions, XF.Material.Forms.UI.Dialogs.Configurations.MaterialSimpleDialogConfiguration configuration) [0x00014] in C:\Users\mhvdi\Documents\OpenSource\XF-Material-Library\XF.Material\UI\Dialogs\MaterialSimpleDialog.xaml.cs:31 
  at UiTest.ViewModels.AboutViewModel.<.ctor>b__17_2 ()
 [0x0006c] in C:\Projects\UiTest\UiTest\UiTest\ViewModels\AboutViewModel.cs:83 }`

And here is my code in App.xaml.cs :

`XF.Material.Forms.Material.Init(this, new MaterialConfiguration`

               {
                    ColorConfiguration = new MaterialColorConfiguration
                    {
                        Background = Color.FromHex("#EAEAEA"),
                        Error = Color.FromHex("#B00020"),
                        OnBackground = Color.FromHex("#000000"),
                        OnError = Color.FromHex("#FFFFFF"),
                        OnPrimary = Color.FromHex("#FFFFFF"),
                        OnSecondary = Color.FromHex("#FFFFFF"),
                        OnSurface = Color.FromHex("#000000"),
                        Primary = Color.FromHex("#2196f3"),
                        PrimaryVariant = Color.FromHex("#03A9F4"),
                        Secondary = Color.FromHex("#29b6f6"),
                        SecondaryVariant = Color.FromHex("#0086c3"),
                        Surface = Color.FromHex("#FFFFFF")
                    }
                });

**Note: for now, I'm only working with Android**
I tried also to use App.xaml to add my configurations as the documentation described, but it didn't work for me.
any help please, I'm new to Xamarin and trying to design a really good UI/UX for my new App.

**Comment by dm-CaT** [comment]
I've faced the same issue. There is no possibility to avoid it when you're configuring Material from code. You have to configure it via resource dictionary. The steps are:
1. Add resources in app.xaml

```
  <Application.Resources>


        <mat:MaterialColorConfiguration x:Key="Material.Color"
            Background="#e1e1e1"
            Error="#B00020"
            OnBackground="#2f3232"
            OnError="#ffffff"
            OnPrimary="#ffffff"
            OnSecondary="#2f3232"
            OnSurface="#2f3232"
            Primary="#585b5b"
            PrimaryVariant="#2f3232"
            Secondary="#ef7d39"
            SecondaryVariant="#ffae67"
            Surface="#f5f5f5" />

        <mat:MaterialConfiguration x:Key="Material.Configuration" ColorConfiguration="{StaticResource Material.Color}"/>

    </Application.Resources>
```
2. Initialize Material in app.xaml.cs **before** InitializeComponent() call.
3. Apply theme from resources to Material after InitializeComponent() call.

```
            Material.Init(this);
            InitializeComponent();
            Material.Use("Material.Configuration");
```

**Comment by TameemHabash** [comment]
@dm-CaT  that's works, thanks.
It still a problem that it does not work as the "ReadMe" file said.
