### ISSUE TITLE
Date picker broken with Xamarin Forms 5 prerelease on ios 14

### ISSUE THREAD

**Issue by softlion** [contrix09/XF-Material-Library#399]
## 🐛 Bug Report

The picker don't work anymore.

It displays a wheel with a fixed value. After clicking a lot it displays a date selector, which seems to be the native iOS one.

### Expected behavior

Works :)

### Reproduction steps
Update to xamarin forms 5 prerelease and test on ios simulator (iphone 8, ios 14.2)

### Configuration

**Version:** 1.8.0-pre8

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by ske66** [comment]
could be a bug with Xamarin Forms 5 rc. Wait for the official release before testing again
