### ISSUE TITLE
What's about reworking MaterialDialogs.ShowAlertAsync to make it really awaitable and return Task<bool> instead?

### ISSUE THREAD

**Issue by agat366** [contrix09/XF-Material-Library#4]
Hi!

I've tried also `MaterialDialogs.ShowAlertAsync` which works fine in general.
However, with current implementation I can't see a way of notifying when the alert (confirmation) box is closed with negative (cancelling) result.

Currently the method is (in general) awaitable, which completes on the confirm popup appearing, however, usually, it doesn't have much sense from the app logic functionality perspective. From my experience, it's rather more important to be able further processing of the app logic after the choice been done.

So, I would suggest to rework it to return `Task<bool>`, which would complete after the used made his choice.

What do you think? I can also fork and apply that update as well if you have no time for that.

**Comment by contrix09** [comment]
Hi.

You have a point, and I like your suggestion. I still have time until the day after tomorrow to apply this, along with the other [feature request](https://github.com/contrix09/XF-Material-Library/issues/3). Can you wait until then? 

I'll update you also if I was not able to apply it. If so, you can just send me a pull request.

**Comment by agat366** [comment]
That's fine. I am not in a rush. Just mentioning that. Also, you might know better if there are some other places you can consider having same logic as well.

**Comment by agat366** [comment]
And speaking of other things... In the confirm dialog, if you have the title too long to fit it into one line, it will be cut as on wrapping it's still going to have height == 40. Is there any reason why you made it fixed?

**Comment by contrix09** [comment]
I can also fix that. I set it to 40 since it was the recommended height, but I forgot to consider long titles.

BTW, thanks for raising these issues/suggestions.

**Comment by contrix09** [comment]
I will also add your suggested implementation for `MaterialDialogs.ShowSnackbarAsync()`.

**Comment by contrix09** [comment]
Version 1.0.6 has been released, adding `MaterialDialogs.ShowConfirmAsync()` which returns `Task<bool>`. Also,  the title of the alert dialog now breaks line when it is long.
