### ISSUE TITLE
Loading Dialog spinner not showing on iOS 14.2

### ISSUE THREAD

**Issue by simonemarra** [contrix09/XF-Material-Library#402]
## 🔙 Regression

The previously working LoadingDialogAsync after updating to iOS14 is not working. The spinner is not showed (but actually there is a "blank space" instead of the circular spinner...). Same configuration is working on Android, I'm using custom colors and theme.

I'm using XF.Material 1.7.6

### Old (and correct) behavior
The Dialog was correctly working, the animation spinner was showed as expected

### Current behavior
The Dialog is missing the spinner. I don't know if it is a problem with iOS14.2 or maybe iOS14.x, since some other users are experiencing the same problem (#195)

### Configuration

**Version:** 1.7.6

**Platform:** 
- [x] :iphone: iOS 14.2
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [x] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by lunjio** [comment]
Try an manually adding the graphic files from library  directly in your project. That helped me on IOS. I'm now facing with similar problem on Android ) Checkbox, and the other graphic files are not displaying.

**Comment by Edgar-Develop** [comment]
Anyone have the solution?

the comment above, does it work?

**Comment by ScarletKuro** [comment]
Have the same problem. Adding the loading_animation.json to Resource of iOS project helped.

**Comment by simonemarra** [comment]
Manually adding the loading_animation.json to Resource folder fixed the issue.
