### ISSUE TITLE
Facing an disapperaring icons in an android and IOS devices? Your are welcome

### ISSUE THREAD

**Issue by lunjio** [contrix09/XF-Material-Library#406]
## 🐛 Bug Report

Some users facing an icons disappearing bug, there are two case - on android, the problem may be the FFImageLoading library, particulary the InitImageHamdler() method. The problem is that, calling this method disables using vectors as image source on android, in our case checkbox, radiobutton on android are represented by vector, mixed with FFImageLoading and using the InitMiageHandler() method, causes the error.  Another case is IOS device, i didn't came to source of error, but an manually adding png files to your IOS project solves the problem.
### Configuration

**Version:** 1.x

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by kerberosargos** [comment]
Yes this bug occurs if **FFImagLoading** implementation codes below after`XF.Material.Droid.Material.Init` `FFImageLoading.Forms.Platform.CachedImageRenderer.Init` should be at above 


I do not get error as below structure

```
            FFImageLoading.Forms.Platform.CachedImageRenderer.Init(enableFastRenderer: true);
            FFImageLoading.Forms.Platform.CachedImageRenderer.InitImageViewHandler();

            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
            XF.Material.Droid.Material.Init(this, savedInstanceState);
```
