### ISSUE TITLE
No longer compatibility with Rg.Plugins.Popup

### ISSUE THREAD

**Issue by felipechavez** [contrix09/XF-Material-Library#407]
## 🐛 Bug Report

After updating Rg.Popup and XF-Material throws an exception

### Reproduction steps
Update both nugets (XF-Material-Library and Rg.Popup) and the following exception appears:

`Method not found: void Rg.Plugins.Popup.Popup.Init(Android.Content.Context,Android.OS.Bundle)`
### Configuration

**Version:** 1.7.7

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmano2188** [comment]
What is the workaround @felipechavez . I'm also facing this issue.

**Comment by RwSgxx** [comment]
good question. @felipechavez how did you solved this, since you closed it.
