### ISSUE TITLE
Make MaterialEntryRenderer public instead of internal

### ISSUE THREAD

**Issue by rafaelagp** [contrix09/XF-Material-Library#408]
## 🚀 Feature Requests

Why is MaterialEntryRenderer currently marked internal instead of public? Please change this.

### Contextualize the feature

Making it public will allow for inheritance. 
For example, I need an integers-only input field, and I'd like to use the MaterialTextField control but I cannot make a custom renderer for it.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Done
