### ISSUE TITLE
iOS doesn't show loading icon on Loading Dialog.

### ISSUE THREAD

**Issue by Edgar-Develop** [contrix09/XF-Material-Library#418]
## 🐛 Bug Report

I'm trying to reproduce a message like "Sending request" with an loading icon but it doesn't appear de icon. 
![image](https://user-images.githubusercontent.com/80066051/110016893-2e3f6f00-7ceb-11eb-8c2b-621608993c63.png)

### Expected behavior
I've reading about some issues but anyone helped me.
### Reproduction steps
This is my code. 
![image](https://user-images.githubusercontent.com/80066051/110017121-765e9180-7ceb-11eb-8c5a-5c31b71c9114.png)

It works perfect in Android.

### Configuration
I put all the configuration like as the Manual description said.
**Version:**
Emulator iPhone version 12 iOS 14.4  1.x
GitHub package version 1.7.7

**Platform:** 
- [X ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Lavankumarkalimisetty** [comment]
None of the Animations like check box, Radio Buttons and loading icon are Working. Can any one has work around please post here.

**Comment by rdelangelhmx** [comment]
I have the same error and aditional error on Debug console.

**[LOTComposition animationNamed:inBundle:]: Animation Not Found**

**Comment by ScarletKuro** [comment]
Have the same problem. Adding the loading_animation.json to Resource of iOS project helped.

**Comment by Slm0nB** [comment]
We are facing the same issue. Did you find a work-around of fix for this issue?

**Comment by Lavankumarkalimisetty** [comment]
@Slm0nB, Add required resources from ("https://github.com/Baseflow/XF-Material-Library/tree/develop/XF.Material/Resources") to your iOS project Resources folder.

**Comment by Slm0nB** [comment]
@Lavankumarkalimisetty Thank you! It works as expected.

**Comment by Edgar-Develop** [comment]
Tanks! It woks too
