### ISSUE TITLE
unable to change loader color in LoadingDialogAsync 

### ISSUE THREAD

**Issue by TheAlphamerc** [contrix09/XF-Material-Library#42]
I am using LoadingDialogAsync to show loading progress on page navigation and it works perfectly.But the color of  circular loader is not matched with my app theme and there is no option in MaterialLoadingDialogConfiguration  to change circular loader color.

**Comment by contrix09** [comment]
Did you use the `Tintcolor` property?

**Comment by TheAlphamerc** [comment]
It works. Thanks Dustin Catap
