### ISSUE TITLE
[Bug | iOS] Spacing between buttons on material dialog

### ISSUE THREAD

**Issue by ScarletKuro** [contrix09/XF-Material-Library#426]
## 🐛 Bug Report

same issue as here https://github.com/Baseflow/XF-Material-Library/issues/83
On iOS 14.4 the dialog looks like this. Both in emulator and real device.
![img](https://i.imgur.com/6jBVbMB.png)

The code is simple
```
var result = await _materialDialog.ConfirmAsync(
                Localization["UNLINK_DEVICE_MESSAGE"],
                Localization["UNLINK_DEVICE_TITLE"],
                Localization["UNLINK_DEVICE_YES"],
                Localization["UNLINK_DEVICE_NO"]);
var yes = result.HasValue && result.Value;
```
All XF.Material settings are stock.
Xamarin.Forms version is **5.0.0.2012** just in case.
### Expected behavior
Expecting the space to be like this as on android
![img](https://i.imgur.com/mkg8GcA.png)

**Version:** 1.7.8

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Slm0nB** [comment]
We are facing the same issue (you are not alone :-))

**Comment by alfredobuon** [comment]
We also face the exact same problem ! And it really makes it hard to use on iOS.

**Comment by bricefriha** [comment]
I noticed this issue as well. It might be easy to fix.
Which dialog is concerned by this?
is it the MaterialAlertDialog.xaml?

Cheers 😉

**Comment by bricefriha** [comment]
The issue will be fixed by PR #431 😉
Unless my code gets roasted in the meantime 😅

**Comment by Whoknow01** [comment]
MaterialInputDialog and SelectChoiceAsync dialogs also has same issue of overlapping..

**Comment by bricefriha** [comment]
@Whoknow01 I fixed some other dialogs that haven't been mentioned here either. But I can't remember if I've fixed those two, I'll be checking this 😉

**Comment by Whoknow01** [comment]
. yes, in some dialog it is appearing correctly except above two. thanks for fixing other dialog

**Comment by bricefriha** [comment]
Pleasure! I'll be fixing these to then 😉

**Comment by bricefriha** [comment]
@martijn00 can't this issue be closed? thanks 🙂

**Comment by ScarletKuro** [comment]
I would appreciate if the new version could be uploaded on nuget. Then I can close this issue.

**Comment by bricefriha** [comment]
This one as been fixed already, we are just waiting for an update of the package

**Comment by ScarletKuro** [comment]
Closing, since there is ticket request for update https://github.com/Baseflow/XF-Material-Library/issues/436

**Comment by bricefriha** [comment]
Cheers @ScarletKuro! 😉
