### ISSUE TITLE
The resource 'Material.LetterSpacing.Button' is not present in the dictionary.

### ISSUE THREAD

**Issue by LeonardoPatti** [contrix09/XF-Material-Library#43]
After initialisation of the package on iOS and Android solution, 
When I use one of component of the package, for example a MaterialRadioButton, I receive an runtime error.
System.Collections.Generic.KeyNotFoundException
The resource 'Material.LetterSpacing.Button' is not present in the dictionary.

**Comment by muhammet-mucahit** [comment]
The problem still exist for me. I have already written XF.Material.Forms.Material.Init(this) in my App.cs but still facing same problem. Any idea?
