### ISSUE TITLE
[iOS] Spacing between buttons in MaterialInputDialog & SelectOptionDialog

### ISSUE THREAD

**Issue by Whoknow01** [contrix09/XF-Material-Library#434]
## 🐛 Bug Report

Negative/Cancel button is overlapping the positive button in few dialog(MaterialInputDialog and SelectChoiceAsync) in IOS only.

**Comment by bricefriha** [comment]
As I mentioned [here](https://github.com/Baseflow/XF-Material-Library/issues/426#issuecomment-907856484) 
I'm on it 😉

**Comment by bricefriha** [comment]
@Whoknow01 The Select Choice looks decent as far as I'm concerned

![image](https://user-images.githubusercontent.com/37577669/131266317-c7f40b58-c2b1-4a9a-8342-8975a13bce30.png)

**Comment by Whoknow01** [comment]
Might be slight more adjustment is required. For reference attaching below image.

<img width="234" alt="Input" src="https://user-images.githubusercontent.com/89747279/131308331-fd1c440d-eda6-49a2-9531-5b364b0a2947.png">
<img width="252" alt="Confirm" src="https://user-images.githubusercontent.com/89747279/131308344-313b5ecb-e57a-4915-8e5f-948d6a15ab64.png">

**Comment by Whoknow01** [comment]
any idea or work around to fix in live app??

**Comment by bricefriha** [comment]
I will fix it. but no I don't know any workaround sorry

**Comment by Whoknow01** [comment]
thanks @bricefriha

**Comment by bricefriha** [comment]
@Whoknow01 Could you tell me on what device you had this result? please 🙂

**Comment by Whoknow01** [comment]
iphone 12 and 5se

**Comment by bricefriha** [comment]
I've tested with the iPhone 12 and I didn't have the same result for the select options 🤔

**Comment by Whoknow01** [comment]
does positive button text “ok” makes any difference ??

**Comment by bricefriha** [comment]
No normally, if the word is shorter the result should be even better, as it's taking less space.
And also, what version of the package have you got? 🙂

**Comment by bricefriha** [comment]
> does positive button text “ok” makes any difference ??

@Whoknow01 I confirm I just tested with "ok" and it works fine on my side

**Comment by onezerotech** [comment]
I am testing this in iPhone 10,11 and 12, and facing the same issue. I am in latest version.

<img width="418" alt="Screenshot 2021-09-25 at 18 46 07" src="https://user-images.githubusercontent.com/83204623/134772905-85b1879a-c687-4fdf-a99a-c8d9c0afbac5.png">

**Comment by bricefriha** [comment]
OK, I know why. My update hasn't been integrated into the release yet.
See issue #436, if you don't know what I'm talking about.

So I can't do anything about it personally sorry.
The first one wasn't fixed so I did it be the second one had been.

So I will create a PR, close this issue and wait for it to be integrated into the next release

**Comment by bricefriha** [comment]
> I am testing this in iPhone 10,11 and 12, and facing the same issue. I am in latest version.
> 
> <img alt="Screenshot 2021-09-25 at 18 46 07" width="418" src="https://user-images.githubusercontent.com/83204623/134772905-85b1879a-c687-4fdf-a99a-c8d9c0afbac5.png">

Actually, this is not related to this issue but to #426 (which had been solved). So that confirms my point! 😄 thanks @onezerotech!
