### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by imabdul-dev** [contrix09/XF-Material-Library#436]
As I saw develop branch is ahead of the master branch and has some dialog buttons margins and some other issues fixes. So, I am here just to ask when will develop branch will merge into the master, and update NuGet packages.

Thanks!

**Comment by bricefriha** [comment]
@martijn00 I think this is a good question 😉

**Comment by onezerotech** [comment]
Hi, When will this be released? Waiting for the

**Comment by onezerotech** [comment]
Hi, When will this be released? Waiting for the alert dialog button (iOS) fix for a long time.
