### ISSUE TITLE
Nugets and .Net Maui

### ISSUE THREAD

**Issue by frankd1996** [contrix09/XF-Material-Library#444]
Hello, my name is Frank, I am a software developer with Xamarin Forms and I use several of their tools, such as XF.Material and LottieXamarin. They are great!
But I would like to know if these tools will be available in .Net Maui and if a migration of them will be possible. If so, do you have an estimated date when this is possible? Greetings.

**Comment by martijn00** [comment]
Make a PR to add support and i will publish a new nuget
