### ISSUE TITLE
MaterialButton Text Color doesn't update on iOS

### ISSUE THREAD

**Issue by eceowl** [contrix09/XF-Material-Library#45]
**Describe the bug**
Trying to change the TextColor property of a MaterialButton on iOS during runtime doesn't work.

**To Reproduce**
Create a MaterialButton and update it's TextColor after initial rendering (via binding, trigger, or code behind)

**Expected behavior**
The TextColor of the MaterialButton should change

**Screenshots**
![textcolor issue](https://user-images.githubusercontent.com/4378173/50848782-22420780-1343-11e9-8275-98a12a61258d.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max Simulator

**Additional context**

**Comment by gaffkins** [comment]
Also text is not updated to.
