### ISSUE TITLE
Can´t set font style (size) on MaterialTextField 

### ISSUE THREAD

**Issue by JPetronilhoNunes** [contrix09/XF-Material-Library#47]
**Describe the bug**
Can´t set font size on MaterialTextField, just as I do on Label width Sytle...

**Comment by contrix09** [comment]
Hi. Right now there is no option to set the font size of the the textfield. It is fixed in `16` units.

**Comment by contrix09** [comment]
Hi, you can now set the input text font size using the property `TextFontSize` and the floating placeholder font size using `FloatingPlaceholderFontSize`. Note that if you only set the font size of the text input, the floating placeholder font size will be set exactly 75% of the text input's font size (e.g. 16 font size of text input * `0.75` = 12 floating placeholder font size).
