### ISSUE TITLE
When I Test Android App in Release, i have this error, but in debug not 

### ISSUE THREAD

**Issue by breakcoding** [contrix09/XF-Material-Library#49]
`[Error] ERR: exClass=android.runtime.JavaProxyThrowable
[Error] ERR: exMsg=System.MissingMethodException: Default constructor not found for type XF.Material.Droid.Effects.MaterialTypeScaleEffect
[Error]   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x0007b] in <5683f1548d9948e4be244166d63ab903>:0 
[Error]   at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00009] in <5683f1548d9948e4be244166d63ab903>:0 
[Error]   at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) [0x00027] in <5683f1548d9948e4be244166d63ab903>:0 
[Error]   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00020] in <5683f1548d9948e4be244166d63ab903>:0 
[Error]   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00000] in <5683f1548d9948e4be244166d63ab903>:0 
[Error]   at System.Activator.CreateInstance (System.Type type) [0x00000] in <5683f1548d9948e4be244166d63ab903>:0 
[Error]   at Xamarin.Forms.Internals.DependencyResolver.ResolveOrCreate (System.Type type, System.Object[] args) [0x00053] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.Effect.Resolve (System.String name) [0x00017] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.RoutingEffect..ctor (System.String effectId) [0x00006] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at XF.Material.Forms.Effects.BaseMaterialEffect..ctor (System.String effectId) [0x00000] in <b82aaf97259b4b829138a9dd7c8bc427>:0 
[Error]   at XF.Material.Forms.Effects.MaterialTypeScaleEffect..ctor (XF.Material.Forms.Resources.Typography.MaterialTypeScale typeScale) [0x00000] in <b82aaf97259b4b829138a9dd7c8bc427>:0 
[Error]   at XF.Material.Forms.Effects.MaterialTypographyEffect.TypeScaleChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue) [0x00053] in <b82aaf97259b4b829138a9dd7c8bc427>:0 
[Error]   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x0012a] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0003d] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle) [0x00000] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.Setter.Apply (Xamarin.Forms.BindableObject target, System.Boolean fromStyle) [0x000c7] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.Style.ApplyCore (Xamarin.Forms.BindableObject bindable, Xamarin.Forms.Style basedOn) [0x0001e] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.Style.Xamarin.Forms.IStyle.Apply (Xamarin.Forms.BindableObject bindable) [0x0003e] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.MergedStyle.SetStyle (Xamarin.Forms.IStyle implicitStyle, System.Collections.Generic.IList`1[T] classStyles, Xamarin.Forms.IStyle style) [0x00167] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.MergedStyle.set_Style (Xamarin.Forms.IStyle value) [0x0000d] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.VisualElement+<>c.<.cctor>b__269_7 (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue) [0x00000] in <2213e65041254f04b27ae6e
[Error] ERR: file=MainActivity.java
[Error] ERR: class=md5ad0086fda8a2a6f068f68d1e85f2c021.MainActivity
[Error] ERR: method=n_onCreate line=-2
[Error] ERR: stack=android.runtime.JavaProxyThrowable: System.MissingMethodException: Default constructor not found for type XF.Material.Droid.Effects.MaterialTypeScaleEffect
[Error]   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x0007b] in <5683f1548d9948e4be244166d63ab903>:0 
[Error]   at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00009] in <5683f1548d9948e4be244166d63ab903>:0 
[Error]   at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) [0x00027] in <5683f1548d9948e4be244166d63ab903>:0 
[Error]   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00020] in <5683f1548d9948e4be244166d63ab903>:0 
[Error]   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00000] in <5683f1548d9948e4be244166d63ab903>:0 
[Error]   at System.Activator.CreateInstance (System.Type type) [0x00000] in <5683f1548d9948e4be244166d63ab903>:0 
[Error]   at Xamarin.Forms.Internals.DependencyResolver.ResolveOrCreate (System.Type type, System.Object[] args) [0x00053] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.Effect.Resolve (System.String name) [0x00017] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.RoutingEffect..ctor (System.String effectId) [0x00006] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at XF.Material.Forms.Effects.BaseMaterialEffect..ctor (System.String effectId) [0x00000] in <b82aaf97259b4b829138a9dd7c8bc427>:0 
[Error]   at XF.Material.Forms.Effects.MaterialTypeScaleEffect..ctor (XF.Material.Forms.Resources.Typography.MaterialTypeScale typeScale) [0x00000] in <b82aaf97259b4b829138a9dd7c8bc427>:0 
[Error]   at XF.Material.Forms.Effects.MaterialTypographyEffect.TypeScaleChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue) [0x00053] in <b82aaf97259b4b829138a9dd7c8bc427>:0 
[Error]   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x0012a] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0003d] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle) [0x00000] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.Setter.Apply (Xamarin.Forms.BindableObject target, System.Boolean fromStyle) [0x000c7] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.Style.ApplyCore (Xamarin.Forms.BindableObject bindable, Xamarin.Forms.Style basedOn) [0x0001e] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.Style.Xamarin.Forms.IStyle.Apply (Xamarin.Forms.BindableObject bindable) [0x0003e] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.MergedStyle.SetStyle (Xamarin.Forms.IStyle implicitStyle, System.Collections.Generic.IList`1[T] classStyles, Xamarin.Forms.IStyle style) [0x00167] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.MergedStyle.set_Style (Xamarin.Forms.IStyle value) [0x0000d] in <2213e65041254f04b27ae6e57d256a86>:0 
[Error]   at Xamarin.Forms.VisualElement+<>c.<.cctor>b__269_7 (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue) [
[Error] ERR: TOTAL BYTES WRITTEN: 28296`

What suppose is the error in Release?
Thank

**Comment by Druffl3** [comment]
> What is your linking options in Android during release?

I am facing the same issue.
My Linking options are "SDK assemblies only".

**Comment by contrix09** [comment]
Hi, can u download the new version `1.4.0.0` and see if this issue still exists.
