### ISSUE TITLE
MaterialTextField: Support for ReturnType & ReturnCommand

### ISSUE THREAD

**Issue by ShahmanTeh** [contrix09/XF-Material-Library#5]
`Xamarin.Forms.Label` 's `ReturnType` and `ReturnCommand` are now supported properties in Xamarin.Forms 3.1 . Is it possible to include these in `MaterialTextField` as well ?

**Comment by contrix09** [comment]
Yes, its possible. Will update you soon.

**Comment by contrix09** [comment]
This feature has been added to version `1.1.0`, please wait for it to be released sooner or later this day.
