### ISSUE TITLE
Adding Command + Clicked capability to MaterialCard or Xamarin's Layouts with Ripple Effect animation

### ISSUE THREAD

**Issue by bubble2k16** [contrix09/XF-Material-Library#55]
**Is your feature request related to a problem? Please describe.**
The Material Effect is currently limited to buttons. But in Google's Material design, the Ripple effect can be applied to many other controls to give the entire application a consistent user experience when clicking on other clickable elements. 

**Describe the solution you'd like**
Adding the Click&Command behaviours to the MaterialCard with Ripple effect. You can also explore exposing the Ripple effect as a behavior that can be attached to any other Xamarin.Forms layouts?

**Describe alternatives you've considered**
There are currently no other alternatives in Xamarin.Forms short of developing a cross-platform wrapper for Material Controls for iOS and Android

Thank you!

**Comment by kfc2000** [comment]
Added a Pull Request for this request. Might want to see if you can incorporate it in.
