### ISSUE TITLE
loading dialog dont display message

### ISSUE THREAD

**Issue by Gr3gorywolf** [contrix09/XF-Material-Library#59]
actually the text is invisible even thought i change the text color using the loadingdialogconfiguration can someone please help me
my dialog:
`
          var conf = new XF.Material.Forms.UI.Dialogs.Configurations.MaterialLoadingDialogConfiguration {
                MessageTextColor = Color.White.MultiplyAlpha(0.8)
       

            };

        var dialogo=   await MaterialDialog.Instance.LoadingDialogAsync("Something is running");
            await Task.Delay(5000);
           await dialogo.DismissAsync();

`

**Comment by contrix09** [comment]
Hi, it seems to be working on my end. Try to set the multiplied alpha color to a darker one, like `Color.Black`.

**Comment by contrix09** [comment]
Hi, havr you resolved this issue?

**Comment by contrix09** [comment]
For now I'm gonna close this issue.

**Comment by Gr3gorywolf** [comment]
sorry for reply it late. and changing the bg color didnt solved my issue idk what is happening

**Comment by contrix09** [comment]
Have you tried not using a style configuration?

**Comment by Gr3gorywolf** [comment]
i'll try it now

**Comment by Gr3gorywolf** [comment]
the same... actually this is the code that im using to call that dialog`  public async void mostrardialogo() {

   
            var loadingDialog = await MaterialDialog.Instance.LoadingDialogAsync(message: "Something is running");
            
            await Task.Delay(5000); // Represents a task that is running.

          await loadingDialog.DismissAsync();
        }`

**Comment by Gr3gorywolf** [comment]
u have discord to show u whats happening?
