### ISSUE TITLE
Custom content on Dialog

### ISSUE THREAD

**Issue by AndreaMinato** [contrix09/XF-Material-Library#63]
**Is your feature request related to a problem? Please describe.**
I would like to have a base Dialog in which i can put any content I wish, similar to what happen on the implementations provided for the inputDialog and the choices.

**Describe the solution you'd like**
Ideally it would be a dialog with a base skin (shadow, backdroup, rounded) and a ContentView (or similar) exposed to be filled with a custom content

btw really nice work with this library!

cheers

**Comment by contrix09** [comment]
Thanks! And yeah, I can add a new method in MaterialDialog.Instance that accepts a view that will be shown as the custom content. Or do you know/suggest a better implementation?

**Comment by AndreaMinato** [comment]
That exactly what I was looking for. thanks for the speed of the response

**Comment by gaffkins** [comment]
how can I remote close custom dialog?
