### ISSUE TITLE
XF.Material Icon was not found in type MaterialTextField

### ISSUE THREAD

**Issue by kwabenaowusujnr** [contrix09/XF-Material-Library#64]
<material:MaterialTextField Placeholder="User" AlwaysShowUnderline="True"  Icon="user1.png"/>

Hi, im using XF.Material version 1.3.1.1 with xamarin forms, visual studio.

Getting **The property 'Icon' was not found in the type MaterialTextField**. Need help urgently.....

**Comment by muhammet-mucahit** [comment]
Did you push the latest changes to the nuget package? It is still the old one.

**Comment by contrix09** [comment]
Hi, I'm just finalizing the release of the new version. The target release will be on Monday.

**Comment by kwabenaowusujnr** [comment]
Great, looking forward to the release then..
