### ISSUE TITLE
Invalid Resource Directory name for fonts		

### ISSUE THREAD

**Issue by livetrackon** [contrix09/XF-Material-Library#7]
**Describe the bug**
Error invalid resource directory name: C:\...\"..."\MonoAndroid81\lp\45\jl\res font "res font".
on Android.

**Comment by contrix09** [comment]
Hi. Can you provide a more specific description of how you encountered this error? Do yoy have a font resource folder in your Resources folder in Android?

**Comment by dzombeast** [comment]
Hi!

@livetrackon Sorry to butt in, but I had similar issue. After doing some research it turned I had to upgrade my android sdk build tools to version 27 smth when using the library.  Perhaps this helps ^^

Cheers

**Comment by contrix09** [comment]
@livetrackon yes, it is required your build tools must be 27.0.0 or greater in order to build the font resource in Android. For now I'm gonna close this issue.
