### ISSUE TITLE
Material Text Field should resize to fit text or allow for line breaks

### ISSUE THREAD

**Issue by eceowl** [contrix09/XF-Material-Library#73]
If the user enters a very long string into a MaterialTextField it doesn't word wrap or resize the text to fit in the box.  Is this possible?

![image](https://user-images.githubusercontent.com/4378173/53041834-ebd3ce00-3452-11e9-8e4b-4711658b75fc.png)

*Note: I have an icon overlayed on top of that MaterialTextField which is what the black spot is.

**Comment by contrix09** [comment]
A multiline text field is not possible at this point since `MaterialTextField` uses the `Entry` control to input text. And only an `Editor` can be used to input multiline text. What I can do for now is to fix the margin of the trailing icon so that the text won't overlap.

**Comment by contrix09** [comment]
Can you provide the XAML code for that particular text field.

**Comment by contrix09** [comment]
I can't replicate the issue of the overlapping icon.

**Comment by eceowl** [comment]
O sorry, I should've clarified. The icon isn't an issue, I actually have disabled your icon and using a grid am placing my own icon on top of the MaterialTextFieldControl. I was doing that so on tap I could animate the arrow and split the address field into it's separate components (Line1, Line2, State, Etc)

**Comment by contrix09** [comment]
I will close this issue. There is a similar [issue](https://github.com/contrix09/XF-Material-Library/issues/94) filed for this feature.
