### ISSUE TITLE
MaterialTextField Choices with dynamic data

### ISSUE THREAD

**Issue by rotsen24154** [contrix09/XF-Material-Library#74]
I have two MaterialTextField, the first has a string's list attached on Choices property and the other one depends of that value to be filled with another string's list (At the beginning this list is empty). But if I choice the first option and try to select the second option throws this exception "The property `Choices` is null or empty", even though the ObservableCollection of the second MaterialTextField was filled after choice the first option.

With the previous nuget works fine.

**Comment by contrix09** [comment]
Hi. Can you provide a sample code of how to replicate this?

**Comment by rotsen24154** [comment]
There is a example project.
[Link example project](https://drive.google.com/open?id=1BOVMVHm0dL-G7JQbtQ8mKRiHi_TNEHaE)

**Comment by rotsen24154** [comment]
I could not create a pull request, but I solved doing this on MaterialTextField.xaml.cs

```
private void SetControl()
{
    trailingIcon.TintColor = this.TextColor;
    persistentUnderline.Color = this.UnderlineColor;
    tapGesture.Command = new Command(() =>
    {
        if (!entry.IsFocused)
        {
            entry.Focus();
        }
    });

    mainTapGesture.Command = new Command(async () =>
    {
        if (Choices == null || Choices?.Count <= 0)
        {
            throw new InvalidOperationException("The property `Choices` is null or empty");
        }
        _choices = GetChoices();

        var result = await MaterialDialog.Instance.SelectChoiceAsync("Select an item", _choices);

        if (result >= 0)
        {
            this.Text = _choices[result];
        }
    });
}
```

**Comment by contrix09** [comment]
Ok thanks. Create a pull request to `dev` branch.
