### ISSUE TITLE
XF.Matrial.Droid not found

### ISSUE THREAD

**Issue by thiagoparabas** [contrix09/XF-Material-Library#79]
Project Xamarin.Forms with Android not Droid found.

![image](https://user-images.githubusercontent.com/47533199/53365125-29d36500-391f-11e9-8a3a-5d1aef146421.png)

![image](https://user-images.githubusercontent.com/47533199/53365029-f1cc2200-391e-11e9-9fb5-ab9604704629.png)

**Comment by contrix09** [comment]
Hi. This is likely caused by the installed `Xamarin.Android.Support.*` packages. The current version of the library targets `MonoAndroid` version `9.0.`, be sure your project is targeting the same version. Update also the your `Xamarin.Forms` and  `Xamarin.Android.Support.*` packages to the *latest* version. Then install the library.

![image](https://user-images.githubusercontent.com/29834445/53375278-c6384e80-3995-11e9-9c3b-72a26cda45f1.png)

**Comment by thiagoparabas** [comment]
Not working man :(

![image](https://user-images.githubusercontent.com/47533199/53408582-98ef9e80-399d-11e9-840d-64053e3153cb.png)

**Comment by shubhambhosale** [comment]
Hi, I have updated all references in the project still having the same issue.

![image](https://user-images.githubusercontent.com/26299688/55781623-3f17e380-5ac8-11e9-83fe-a8356dc369df.png)

**Comment by ghost** [comment]
I'm having the same problem:
![image](https://user-images.githubusercontent.com/61947354/76169412-0bf52e80-6135-11ea-8d51-7c791c335eca.png)
![image](https://user-images.githubusercontent.com/61947354/76169428-3a730980-6135-11ea-8045-41ea3e83df4d.png)
although all installed Android dependencies are current (I updated them before installing the library):
![image](https://user-images.githubusercontent.com/61947354/76169481-e0bf0f00-6135-11ea-8173-87ae13392c84.png)
Any ideas what else could be wrong?

**Comment by Luismimultimedia** [comment]
Hello,

i am facing the same issue, the error says "it doesnt found Droid in the name space 'XF.Material'".
my package nugets are :
Xamarin.Forms v4.5.0.396
Xamarin.Essentials v1.5.1
XF.Material v1.6.1
Xamarin.Android.Support.* v28.0.0.3

My target android is Android10, Api 29 (Q)

I also download https://github.com/Baseflow/XF-Material-Library/issues/57#issuecomment-466857381 the example and i update on the version of Xamarin.Forms and XF.Material i have and the problem perssist.

I hope if someone can help me, i will be so glad.

Thank you.

**Comment by gbadwaik2706** [comment]
It worked after migrating the project to AndroidX and changing the target and compiling version to Android 10 - Q
