### ISSUE TITLE
Spacing between action buttons on material dialog cancel | ok

### ISSUE THREAD

**Issue by vjsystematix** [contrix09/XF-Material-Library#83]
How can give space between action buttons ok and cancel on material dialog

**Comment by contrix09** [comment]
Sorry but you can't. The spacing is set to a static `8`.

**Comment by vjsystematix** [comment]
But the view is not look good Ok and | are overlap

**Comment by contrix09** [comment]
This seems to be a bug. Can you provide what device you are using?

**Comment by vjsystematix** [comment]
> This seems to be a bug. Can you provide what device you are using?

I am using IPhone X, iOS 8+

**Comment by contrix09** [comment]
Can you provide the code you used to show this dialog, including the custom configuration style.

**Comment by contrix09** [comment]
I used the following code to show the dialog:
```c#
await MaterialDialog.Instance.SelectChoiceAsync("Select jobs", new string[]
{
    "Choice 1",
    "Choice 2",
    "Choice 3",
    "Choice 4",
    "Choice 5",
    "Chouce 6",
}, new XF.Material.Forms.UI.Dialogs.Configurations.MaterialConfirmationDialogConfiguration
{
    TintColor = Color.White,
    BackgroundColor = Material.Color.Primary,
    TextColor = Color.White.MultiplyAlpha(0.88),
    TitleTextColor = Color.White
});
```

And used an iPhone X simulator running iOS 12 <br/>
![image](https://user-images.githubusercontent.com/29834445/53608921-95f3e880-3bff-11e9-8cfd-ab24359744f4.png)

**Comment by vjsystematix** [comment]
Thanks for replying, The exact version of IPhone X is 11.2. and here is the code which I Used.

var confirmationDialogConfiguration = new MaterialConfirmationDialogConfiguration
            {
                CornerRadius = 8,
                ButtonAllCaps = false,
     };
            var choices = dates.ToArray();

int wasConfirmed = await MaterialDialog.Instance.SelectChoiceAsync("Select Date",choices, confirmationDialogConfiguration);

            if (wasConfirmed >= 0)
            {
                //int index = view.SelectedIndex;
                //choices.GetValue(wasConfirmed)
                var value = choices.GetValue(wasConfirmed);
            }

**Comment by vjsystematix** [comment]
Any update on this?

**Comment by contrix09** [comment]
Hi. I can't replicate the issue. I even tried testing on a physical device, iPhone X running iOS 12.1.2.

![image](https://user-images.githubusercontent.com/29834445/53863602-920ffe00-4025-11e9-8f9d-439e04d36cc1.png)

**Comment by vjsystematix** [comment]
which version of XF material are you used. can you please run this on Iphone X iOS 11.2.

**Comment by contrix09** [comment]
Ok. Will try this on iOS 11.2.

**Comment by vjsystematix** [comment]
> Ok. Will try this on iOS 11.2.

Thanks for your help, really appreciable. it would be good if you will do this quick as i have to released the version of my app.

**Comment by vjsystematix** [comment]
Hi @contrix09 did you get time to look in this point. we have tested in android device it's look fine but in iOS it seems overlap

**Comment by contrix09** [comment]
Hi, sorry for the late reply, been busy.

But I still can't replicate the issue.
![image](https://user-images.githubusercontent.com/29834445/54245981-04289b80-456e-11e9-846c-70dc2c935a19.png)

```c#
var choices = new string[] { "Choice 1", "Choice 2" };
var config = new MaterialConfirmationDialogConfiguration
{
    CornerRadius = 8,
    ButtonAllCaps = false
};
await MaterialDialog.Instance.SelectChoiceAsync("Select one item:", choices, configuration: config);
```

**Comment by vjsystematix** [comment]
Thanks for adding new params in SelectChoiceAsync Method. It's work now. I am using 1.4.1.1 version of this library.
