### ISSUE TITLE
Xamarin.Forms.Xaml.XamlParseException: No embeddedresource found for XF.Material.Forms.UI.MaterialTextField

### ISSUE THREAD

**Issue by thiagoparabas** [contrix09/XF-Material-Library#85]
Not working using MaterialTextField.

![image](https://user-images.githubusercontent.com/47533199/53510307-6ed0d600-3a9c-11e9-847a-801f4f477a52.png)

![image](https://user-images.githubusercontent.com/47533199/53510286-5d87c980-3a9c-11e9-811e-7ca4a3c0c8b4.png)

**Comment by thiagoparabas** [comment]
Several components depend on MatrialNavigationPage, without which it generates this error.

You need to remove this dependencies from the components.

**Comment by contrix09** [comment]
Hi. All components can work individually without the `MaterialNavigationPage`. Can you provide a complete sample code to reproduce this. I can't reproduce it with the given screenshot of the code above.
