### ISSUE TITLE
Two MaterialCheckboxGroup use the same SelectedIndices list?

### ISSUE THREAD

**Issue by gaffkins** [contrix09/XF-Material-Library#89]
I have two separate MaterialCheckboxGroup on on page. 
When I choose some options from first list I have from example SelectedIndices.Count = 2. 
Next, in second list i choose one option.
Next I open again first list and select one option. I should have  SelectIndices.Count = 3 but I have SelectedIndices.Count =4.

**Comment by contrix09** [comment]
Hi. Can you provide a repro code?

**Comment by gaffkins** [comment]
Ok, few bugs in one project.
1. MaterialCheckboxGroup:
Step to reproduce:
1. Click Add events button and check first item for example.
2. Click Add sections and look in console. Sections Count is one.
3. Click first item in sections and deselect it.
4. Open Events. Events Count in console is zero.

2. MaterialTextField Text property not update button label.

3. Rounded corner button:
After last update my circle button got strange shape. Width, height = 64, cornerRadius = 32

FastTest.zip
