### ISSUE TITLE
SelectChoicesAsync, option to set SelectIndex before is open

### ISSUE THREAD

**Issue by breakcoding** [contrix09/XF-Material-Library#9]
I thinks is great a option like param what indices are selected when the MaterialDialog is appearing

Thanks this is a great job is so usefull!! Congratulations!

**Comment by contrix09** [comment]
Hi, and thank you for using this library.

I think this is possible. I will update you soon.

**Comment by breakcoding** [comment]
Excelent!! Great work

**Comment by contrix09** [comment]
Hi, version `1.1.1` has been released.
