### ISSUE TITLE
Material Card Corner Radius not working iOS

### ISSUE THREAD

**Issue by muhammetsahin** [contrix09/XF-Material-Library#90]
Material Card corner radius not working on iOS. Android is working fine.

Here is an iOS screenshot:

![simulator screen shot - iphone 6 - 2019-02-28 at 23 00 10](https://user-images.githubusercontent.com/2045788/53594769-9dd66d00-3bac-11e9-9606-4e0711ced381.png)

and Android screenshot:
![image](https://user-images.githubusercontent.com/2045788/53594857-dc6c2780-3bac-11e9-8350-e78440f07fb0.png)

And code sample:

` <renderedViews:HorizontalListView
            x:Name="StoryListView"
            Margin="0,12,0,0"
            CollectionPadding="24,0,24,0"
            ItemHeight="200"
            ItemSpacing="10"
            ItemWidth="180"
            ItemsSource="{Binding TimelineList}"
            SnapStyle="None">
            <renderedViews:HorizontalListView.ItemTemplate>
              <DataTemplate>
                <ViewCell>
                  <Grid Padding="0,0,0,20">
                    <material:MaterialCard
                      Padding="0"
                      BackgroundColor="White"
                      CornerRadius="10"
                      IsClickable="True">
                      <Grid Padding="0" RowSpacing="0">
                        <Grid.RowDefinitions>
                          <RowDefinition Height="4*" />
                          <RowDefinition Height="3*" />
                        </Grid.RowDefinitions>
                        <Image
                          Grid.Row="0"
                          Aspect="AspectFill"
                          HorizontalOptions="Fill"
                          Source="{Binding Image}"
                          VerticalOptions="Fill" />
                        <StackLayout
                          Grid.Row="1"
                          Padding="12,12,12,12"
                          VerticalOptions="CenterAndExpand">
                          <Label
                            FontFamily="{StaticResource LifeFontFamily}"
                            FontSize="13"
                            Text="{Binding When}"
                            TextColor="{DynamicResource SecondaryDark}" />
                          <Label
                            FontFamily="{StaticResource LifeFontFamily}"
                            FontSize="12"
                            LineBreakMode="TailTruncation"
                            MaxLines="1"
                            Text="{Binding EventTitle}"
                            TextColor="{DynamicResource SecondaryDark}" />
                          <Label
                            FontFamily="{StaticResource LifeFontFamily}"
                            FontSize="12"
                            LineBreakMode="TailTruncation"
                            MaxLines="1"
                            Text="{Binding EventDescription}"
                            TextColor="{DynamicResource SecondaryDark}" />
                        </StackLayout>
                      </Grid>
                    </material:MaterialCard>
                  </Grid>
                </ViewCell>
              </DataTemplate>
            </renderedViews:HorizontalListView.ItemTemplate>
          </renderedViews:HorizontalListView>
`

I used 1.4.0.1 version.

Any ideas??

Thank you.

**Comment by rotsen24154** [comment]
Yes, it's a bug from Xamarin and it's been open for a year.
[Xamarin GitHub](https://github.com/xamarin/Xamarin.Forms/issues/2405).

**Comment by muhammetsahin** [comment]
I think, I solved the issue.

Just added this code 
`IsClippedToBounds="True"`

and problem solved.
