### ISSUE TITLE
Provide a UnderlineVisible and/or UnderlineActiveColor bindable property

### ISSUE THREAD

**Issue by fabcall** [contrix09/XF-Material-Library#92]
**Is your feature request related to a problem? Please describe.**
As of now, one can control the color of the MaterialTextField's underline using the TintColorProperty. Any change made to this prop also affects the floating placeholder. But, sometimes, you may wish to not have a underline at all, eg. when you place a MaterialTextField inside a TextCell. I attached an example at the Additional Context. It's from an iOS app, but the Android one is equal. You can see there's a really opaque line under the textfield, but it belongs to the cell itself.

**Describe the solution you'd like**
Having an option to control the inactive/active color would be nice, as one could simply set it as transparent.

**Describe alternatives you've considered**
An alternative could be an IsUnderlineVisible property, which would control whether the line is rendered or not.

**Additional context**
`<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/31/80/a9/3180a963-a930-3b84-57ec-49b58185c91c/mzl.bafeurhs.png/230x0w.jpg" />`

**Comment by moreirawebmaster** [comment]
PR for disable underline: https://github.com/contrix09/XF-Material-Library/pull/93

**Comment by contrix09** [comment]
You can disable the underline from showing/animating using the new property `ShouldAnimateUnderline`.
