### ISSUE TITLE
Access colors in XAML

### ISSUE THREAD

**Issue by daniel-van-niekerk** [contrix09/XF-Material-Library#96]
How can I access the color resources in XAML?

I tried adding the XF.Material library as a xmlns like this:

`xmlns:material="clr-namespace:XF.Material.Forms.Resources;assembly=XF.Material.Forms"`

But I can't seem to get the color properties that is in XF.Material.Forms.Material.Color.Primary.

I'm guessing I'm using XAML wrong, thanks for any help.

**Comment by contrix09** [comment]
You can access them using the `DynamicResource` extension in XAML. 

Like this:
```xml
<Button BackgroundColor="{DynamicResource Material.Color.Primary}"
        Text="Click Me!" />
```

**Comment by daniel-van-niekerk** [comment]
Thanks!
