### ISSUE TITLE
Material card lost border top?

### ISSUE THREAD

**Issue by Jululu** [contrix09/XF-Material-Library#98]
**Describe the bug**
The card on a white background before had a border when you used elevation = 1 and now you can not see any border except the bottom border

**Expected behavior**
Card with all borders

**Screenshots**
![screenshot_1](https://user-images.githubusercontent.com/8309379/53871323-59a7fa00-3ffc-11e9-983f-272a275fed70.png)

https://ibb.co/nfKsTqr

**Smartphone (please complete the following information):**
 - Device: Huawei honor 8X, Google pixel 2 XL
 - OS: Android
 - Version: 1.4.0.4

**Additional context**

**Comment by contrix09** [comment]
Do you know the last version this was working? I'll include the fix for this if any on my next release, which will be tomorrow.

**Comment by Jululu** [comment]
1.3.1.1

**Comment by contrix09** [comment]
Can you give me your `MaterialCard` XAML?

**Comment by Jululu** [comment]
<material:MaterialCard
            Margin="0,0,0,5"
            Padding="10"
            BorderColor="#e2e2e2"
            CornerRadius="0"
            Elevation="1"
            HorizontalOptions="FillAndExpand"
            VerticalOptions="FillAndExpand">
            <StackLayout HorizontalOptions="FillAndExpand"
Orientation="Horizontal">
                <StackLayout
                    Margin="-10,-10,0,-10"
                    BackgroundColor="{Binding IsSentColor}"
                    HorizontalOptions="Start"
                    VerticalOptions="FillAndExpand"
                    WidthRequest="10" />
                <StackLayout
                    Margin="0"
                    HorizontalOptions="FillAndExpand"
                    Orientation="Horizontal"
                    VerticalOptions="Start">
                    <StackLayout HorizontalOptions="StartAndExpand"
Orientation="Horizontal">
                        <iconize:IconImage
                            Icon="fas-calendar-alt"
                            IconColor="#01baad"
                            IconSize="18"
                            VerticalOptions="CenterAndExpand"
                            WidthRequest="25" />
                        <Label
                            FontSize="12"
                            Text="{Binding Date}"
                            VerticalOptions="Start" />
                    </StackLayout>
                    <StackLayout HorizontalOptions="End"
Orientation="Horizontal">
                        <Label
                            FontSize="12"
                            Text="{Binding Description}"
                            VerticalOptions="Start" />
                        <iconize:IconImage
                            Icon="fas-syringe"
                            IconColor="#01baad"
                            IconSize="18"
                            VerticalOptions="CenterAndExpand"
                            WidthRequest="25" />
                    </StackLayout>
                </StackLayout>
            </StackLayout>
        </material:MaterialCard>

**Comment by contrix09** [comment]
Hi. I tested this on the new version to be released tomorrow. Running Google Pixel 2 XL Emulator on Android 8.0.
![image](https://user-images.githubusercontent.com/29834445/53881417-9bfa2700-404e-11e9-956e-a547d78565fb.png)

**Comment by Jululu** [comment]
Perfect!! I will test tomorrow then.

Thank you
